---
title: "ExampleDay37.Rmd"
author: "Math 236"
date: "12/2/2021"
output: html_document
---

```{r,fig.width=5, fig.height=5}
x = c(1,2,3,4,5,6)
y = c(7,2,1,3,7,7)
plot(x,y,pch=19,ylim=c(0,10))
grid()
```

```{r}
(A = cbind(x^0,x))
(xhat = solve(t(A) %*% A, t(A) %*% y))
```
```{r}
(xhat = solve(t(A) %*% A, t(A) %*% y))
```

```{r,fig.width=5, fig.height=5}
#plot the original set of points
plot(x,y,pch=19,xlim=c(0,7),ylim=c(0,10), main='the best-fit linear function')

# generate points for the fitted line and plot it
tt = seq(0,7,len=100)  
lines(tt,xhat[1]+xhat[2]*tt,col='blue')

# get yhat
yhat = A %*% xhat

#add yhat to the plot


#put the original points back on the plot last so we can see them 
points(x,y,pch=19,col="black")
grid()
```
```{r,fig.width=5, fig.height=5}
#plot the original set of points
(A = cbind(x^0,x,x^2))
(xhat = solve(t(A) %*% A, t(A) %*% y))
plot(x,y,pch=19,xlim=c(0,7),ylim=c(0,10), main='the best-fit linear function')

# generate points for the fitted line and plot it
tt = seq(0,7,len=100)  
lines(tt,xhat[1]+xhat[2]*tt+xhat[3]*tt^2,col='blue')

# get yhat
yhat = A %*% xhat
#put the original points back on the plot last so we can see them 
points(x,y,pch=19,col="black")
grid()
```
