<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 1 Eigenvectors | 06-eigenvectors.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 1 Eigenvectors | 06-eigenvectors.knit" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 1 Eigenvectors | 06-eigenvectors.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>


<link rel="stylesheet" href="m236.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">MATH 236: Linear Algebra</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#eigenvectors"><i class="fa fa-check"></i><b>1</b> Eigenvectors</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#computing-eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>1.1</b> Computing Eigenvectors and Eigenvalues</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#diagonalization"><i class="fa fa-check"></i><b>1.2</b> Diagonalization</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#rental-car-example"><i class="fa fa-check"></i><b>1.3</b> Rental Car Example</a></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#northern-spotted-owl"><i class="fa fa-check"></i><b>1.4</b> Northern Spotted Owl</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path=""><a href="#the-dynamical-system"><i class="fa fa-check"></i><b>1.4.1</b> The Dynamical System</a></li>
<li class="chapter" data-level="1.4.2" data-path=""><a href="#eigenanalysis"><i class="fa fa-check"></i><b>1.4.2</b> Eigenanalysis</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:title:end-->
<!--bookdown:title:start-->
<div id="eigenvectors" class="section level1" number="1">
<h1><span class="header-section-number">Section 1</span> Eigenvectors</h1>
<p><a href="https://github.com/Tom-Halverson/math236_s21/blob/main/06-eigenvectors.Rmd">Download this Rmd file</a></p>
<div id="computing-eigenvectors-and-eigenvalues" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Computing Eigenvectors and Eigenvalues</h2>
<p>To compute eigenvalues and eigenvectors in <code>R</code> we use the <code>eigen</code> command. For example if our matrix is</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">A =</span>  <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">14</span>,<span class="sc">-</span><span class="dv">20</span>,<span class="sc">-</span><span class="dv">23</span>),<span class="fu">c</span>(<span class="dv">13</span>,<span class="dv">19</span>,<span class="dv">19</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">2</span>,<span class="dv">1</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]  -14   13   -2
## [2,]  -20   19   -2
## [3,]  -23   19    1</code></pre>
<p>Then we compute its eigenvalues and eigenvectors as</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  6  3 -3
## 
## $vectors
##            [,1]       [,2]      [,3]
## [1,] -0.2672612 -0.4082483 0.5773503
## [2,] -0.5345225 -0.4082483 0.5773503
## [3,] -0.8017837  0.8164966 0.5773503</code></pre>
<p>One thing to notice about the eigenvectors is that they are scaled to have length one (they are <strong>unit vectors</strong>). So they often do not look like what we expect. Note for example that the first vector above is a multiple of <span class="math inline">\((1,2,3)^T\)</span>, the second is a multiple of <span class="math inline">\((-1,-1,2)^T\)</span> and the third is a multiple of <span class="math inline">\((1,1,1)^T\)</span>.</p>
<p>We can extract the eigenvectors and eigenvalues as follows</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">=</span> <span class="fu">eigen</span>(A)<span class="sc">$</span>values</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>vecs <span class="ot">=</span> <span class="fu">eigen</span>(A)<span class="sc">$</span>vectors</span></code></pre></div>
<p>Then, for example, we can see if a vector is an eigenvector as follows. Here I will check the first eigenvalue and first eigenvector:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lambda1 <span class="ot">=</span> vals[<span class="dv">1</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">=</span> vecs[,<span class="dv">1</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> v1</span></code></pre></div>
<pre><code>##           [,1]
## [1,] -1.603567
## [2,] -3.207135
## [3,] -4.810702</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lambda1 <span class="sc">*</span> v1</span></code></pre></div>
<pre><code>## [1] -1.603567 -3.207135 -4.810702</code></pre>
<p>From this, we see that <span class="math inline">\(A v_1 = \lambda_1 v_1\)</span>.</p>
<p>Recall that every scalar multiple of an eigenvector is also an eigenvector of that same eigenvalue. The vectors are currently scaled to have length 1. Another useful scaling is to have them sum to 1. You can accomplish this by dividing them by the sum of their entries. For example,</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">=</span> v1<span class="sc">/</span><span class="fu">sum</span>(v1)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>v1</span></code></pre></div>
<pre><code>## [1] 0.1666667 0.3333333 0.5000000</code></pre>
</div>
<div id="diagonalization" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Diagonalization</h2>
<p>In class we diagonalized a few matrices. Here we show how to do this in <code>R</code>.</p>
<ol style="list-style-type: lower-alpha">
<li>Here is the first matrix from the checkpoint question CP-5.3.</li>
</ol>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">A =</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">6</span>,<span class="sc">-</span><span class="dv">7</span>),<span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">2</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   -5    6   -2
## [2,]   -6    7   -2
## [3,]   -7    8   -2</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">=</span> <span class="fu">eigen</span>(A)<span class="sc">$</span>values</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>vals</span></code></pre></div>
<pre><code>## [1]  1.000000e+00 -1.000000e+00 -3.766534e-15</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>vecs <span class="ot">=</span> <span class="fu">eigen</span>(A)<span class="sc">$</span>vectors</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>vecs</span></code></pre></div>
<pre><code>##            [,1]      [,2]       [,3]
## [1,] -0.2672612 0.5773503 -0.6666667
## [2,] -0.5345225 0.5773503 -0.6666667
## [3,] -0.8017837 0.5773503 -0.3333333</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(vecs) <span class="sc">%*%</span> A <span class="sc">%*%</span> vecs</span></code></pre></div>
<pre><code>##              [,1]          [,2]          [,3]
## [1,] 1.000000e+00  3.355686e-15 -6.554309e-16
## [2,] 6.661338e-15 -1.000000e+00  8.881784e-15
## [3,] 4.272762e-15 -3.076740e-15  1.776357e-15</code></pre>
<p>Here, we are diagonalizing <span class="math inline">\(A\)</span> by multiplying <span class="math inline">\(P^{-1} A P = D\)</span> where <span class="math inline">\(P\)</span> is the matrix of eigenvectors and <span class="math inline">\(D\)</span> is the diagonal matrix of eigenvalues.</p>
<p>We can use <code>zapsmall</code> to round or “zap” very small numbers to 0, and it then looks more like what we are expecting.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">zapsmall</span>(<span class="fu">solve</span>(vecs) <span class="sc">%*%</span> A <span class="sc">%*%</span> vecs)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0   -1    0
## [3,]    0    0    0</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Now we diagonalize the second matrix from CP-5.3 You will recall that this one has a repeated eigenvalue (algebraic multiplicity 2), but it has a 2-dimensional eigenspace (geometric multiplicity 2), so it is digonalizable.</li>
</ol>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">2</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>),<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">0</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(B)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  4  4 -2
## 
## $vectors
##            [,1]      [,2]       [,3]
## [1,]  0.9128709 0.0000000 -0.4082483
## [2,] -0.1825742 0.8944272 -0.4082483
## [3,]  0.3651484 0.4472136  0.8164966</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">=</span> <span class="fu">eigen</span>(B)<span class="sc">$</span>values</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>vecs <span class="ot">=</span> <span class="fu">eigen</span>(B)<span class="sc">$</span>vectors</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">zapsmall</span>(<span class="fu">solve</span>(vecs) <span class="sc">%*%</span> B <span class="sc">%*%</span> vecs)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    4    0    0
## [2,]    0    4    0
## [3,]    0    0   -2</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>The third matrix from CP-5.3 is not diagonalizable. It has an eigenvalue of algebraic multiplicity 2 and geometric multiplicity 1. Note that it gives the same two eigenvectors for <span class="math inline">\(v_2\)</span> and <span class="math inline">\(v_3\)</span>, because the eigenspace <span class="math inline">\(E_2\)</span> is only 1 dimensional.</li>
</ol>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>C <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">3</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">1</span>),<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(C)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 3 2 2
## 
## $vectors
##            [,1]       [,2]       [,3]
## [1,]  0.8017837  0.5773503  0.5773503
## [2,] -0.2672612 -0.5773503 -0.5773503
## [3,]  0.5345225  0.5773503  0.5773503</code></pre>
</div>
<div id="rental-car-example" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Rental Car Example</h2>
<p>In problem PS 3.8, you studied a transition matrix for where cars got returned if they are rented from one of three rental locations: St. Paul, Rochester, and Duluth. Note that the columns of this matrix are probablilities, and as such, the are nonnegative and sum to 1. Such a matrix is called a <strong>Markov</strong> or <strong>stochastic</strong> matrix.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>StP <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">85</span>,.<span class="dv">09</span>,.<span class="dv">06</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>Roch <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">30</span>,.<span class="dv">60</span>,.<span class="dv">10</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>Dul <span class="ot">=</span> <span class="fu">c</span>(.<span class="dv">35</span>,.<span class="dv">05</span>,.<span class="dv">60</span>) </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>M <span class="ot">=</span> <span class="fu">cbind</span>(StP,Roch,Dul)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(M) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;StP&quot;</span>,<span class="st">&quot;Roch&quot;</span>,<span class="st">&quot;Dul&quot;</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>M</span></code></pre></div>
<pre><code>##       StP Roch  Dul
## StP  0.85  0.3 0.35
## Roch 0.09  0.6 0.05
## Dul  0.06  0.1 0.60</code></pre>
<p>In this assignment you imagined that there were 20 cars at each location, i.e., <code>v = cbind(20,20,20)</code> and you applied the matrix over and over again to this vector watching it converge to a steady state.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">20</span>,<span class="dv">20</span>,<span class="dv">20</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span> <span class="dv">100</span>) { v <span class="ot">=</span> M <span class="sc">%*%</span> v }</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##           [,1]
## StP  40.969163
## Roch 10.308370
## Dul   8.722467</code></pre>
<p>Stochastic matrices always have eigenvalue <span class="math inline">\(\lambda = 1\)</span>. As can be seen here:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(M)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 1.000+0.000000i 0.525+0.037081i 0.525-0.037081i
## 
## $vectors
##              [,1]                  [,2]                  [,3]
## [1,] 0.9497414+0i  0.6201737+0.0000000i  0.6201737+0.0000000i
## [2,] 0.2389672+0i -0.3100868-0.4599331i -0.3100868+0.4599331i
## [3,] 0.2022030+0i -0.3100868+0.4599331i -0.3100868-0.4599331i</code></pre>
<p>Note that the first eigenvalue is 1, and that the second and third eigenvalues (and eigenvectors) are complex and have both real and imaginary parts. If some of the eigenvalues have imaginary parts, then it outputs them all in complex form.</p>
<p>Here we extract just the real part of the first eigenvector (since its imaginary part is 0), and we rescale it both to sum to 1 and to sum to 60.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">=</span> <span class="fu">Re</span>(<span class="fu">eigen</span>(M)<span class="sc">$</span>vectors[,<span class="dv">1</span>])</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">v =</span> v <span class="sc">/</span><span class="fu">sum</span>(v))</span></code></pre></div>
<pre><code>## [1] 0.6828194 0.1718062 0.1453744</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="dv">60</span><span class="sc">*</span>v</span></code></pre></div>
<pre><code>## [1] 40.969163 10.308370  8.722467</code></pre>
<p>Notice that this is the <em>exact same</em> as the steady-state vector that we got by iterating. The steady-state that this system wants to be in — with 40.97 cars in St. Paul, 10.31 cars in Rochester, and 8.72 cars in Duluth. It makes sense that a steady-state vector is an eigenvector with eigenvalue <span class="math inline">\(\lambda = 1\)</span>. That the system converges to this state is eigen-magic that we will learn about soon.</p>
</div>
<div id="northern-spotted-owl" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Northern Spotted Owl</h2>
<p>This is the opening example in Chapter 5 of the textbook on page 265. It comes from a 1992 study of the northern spotted owl, which was threatened with extinction due to the loss of forest habitat due to logging in the Pacific Northwest. This is currently a story featured in an NPR Podcast called <a href="https://www.npr.org/podcasts/906829608/timber-wars">Timber Wars</a>.</p>
<div id="the-dynamical-system" class="section level3" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> The Dynamical System</h3>
<p>The vector
<span class="math display">\[
x_n = \begin{bmatrix} j_n \\ s_n \\ a_n \end{bmatrix}
\]</span>
is an <em>age-stage</em> vector in which <span class="math inline">\(j_n, s_n\)</span>, and <span class="math inline">\(a_n\)</span> are the number of female owls in the juvenile (up to 1 year), subadult (1-2 year), and adult (over 2 year) age groups in year <span class="math inline">\(n\)</span>.</p>
<p>The dynamics that take us from one year to the next is given by, the recursive relation <span class="math inline">\(x_{n+1} = A x+n\)</span>, where <span class="math inline">\(A\)</span> is the matrix shown here. This is an age-stage matrix model that was published in <a href="https://www.fs.usda.gov/treesearch/pubs/3519"><em>Conservation Biology</em></a>.
<span class="math display">\[
\begin{bmatrix} j_{n+1} \\ s_{n+1} \\ a_{n+1} \end{bmatrix}
= 
\begin{bmatrix} 0 &amp; 0 &amp; 0.33 \\ 0.18 &amp; 0 &amp; 0 \\ 0 &amp; 0.71 &amp; 0.94 \end{bmatrix}
\begin{bmatrix} j_n \\ s_n \\ a_n \end{bmatrix}
\]</span>
If we multiply this system out, we get
<span class="math display">\[
\begin{array} {rcl}
j_{n+1} &amp;=&amp; 0.33 a_n    \\
s_{n+1} &amp;=&amp; 0.18 j_n     \\
a_{n+1} &amp;=&amp; 0.71 s_n + 0.94 a_n    
\end{array}
\]</span>
We see that, in this model, 0.33 represents the fertility or <em>fecundity</em> rate. That is, it is the proportion of new juveniles next year to adults this year (the proportion of offspring the adult population is producing). The 0.18 is the survival rate from juvenile to subadult, 0.71 is the survival rate from subadult to adult, and 0.94 proportion of adults that survive from one year to the next.</p>
<p>To see the dynamics play out over time, we will start with an original population of owls is distributed into age groups as follows.
<span class="math display">\[
x_0 = \begin{bmatrix} 100 \\ 76 \\ 502 \end{bmatrix}
\]</span>
We will write a loop to apply the matrix <span class="math inline">\(A\)</span> over and over again. This time we will make a table and store each value in the table.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.18</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">71</span>),<span class="fu">c</span>(<span class="fl">0.33</span>,<span class="dv">0</span>,<span class="fl">0.94</span>)) <span class="co"># the population dynamics matrix</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>x0 <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">76</span>,<span class="dv">502</span>) <span class="co"># the inital value</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">10</span>  <span class="co"># iterate N=10 times</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="at">nrow=</span><span class="fu">nrow</span>(A),<span class="at">ncol=</span>N<span class="sc">+</span><span class="dv">1</span>) <span class="co"># initialize an all 0 matrix to store values in</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>X[,<span class="dv">1</span>] <span class="ot">=</span> x0 <span class="co"># the first column is the initial population</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(N<span class="sc">+</span><span class="dv">1</span>)) {  <span class="co"># loopn from 2 to N+1</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  X[,i] <span class="ot">=</span> A <span class="sc">%*%</span> X[,i<span class="dv">-1</span>] <span class="co"># Apply A to column i-1 and put the value in column i</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>X <span class="co"># display the table</span></span></code></pre></div>
<pre><code>##      [,1]   [,2]     [,3]     [,4]      [,5]      [,6]     [,7]      [,8]
## [1,]  100 165.66 173.5272 167.3330 164.27953 161.74110 159.0937 156.47643
## [2,]   76  18.00  29.8188  31.2349  30.11993  29.57032  29.1134  28.63687
## [3,]  502 525.84 507.0696 497.8168 490.12454 482.10222 474.1710 466.39127
##           [,9]     [,10]     [,11]
## [1,] 153.90912 151.38419 148.90038
## [2,]  28.16576  27.70364  27.24915
## [3,] 458.73997 451.21326 443.81005</code></pre>
<p>Having saved the information, we can now plot the data, Note that it appears to support the claim the claim that the owls are threatened with extinction.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>tot <span class="ot">=</span> X[<span class="dv">1</span>,] <span class="sc">+</span> X[<span class="dv">2</span>,] <span class="sc">+</span> X[<span class="dv">3</span>,]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,N<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t,X[<span class="dv">1</span>,],<span class="at">type=</span><span class="st">&#39;l&#39;</span>,<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1000</span>),<span class="at">ylab=</span><span class="st">&quot;population&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;year&quot;</span>,<span class="at">main=</span><span class="st">&quot;Spotted Owl Population&quot;</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">1</span>,],<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">8</span>, <span class="dv">1050</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;juvenile&quot;</span>, <span class="st">&quot;subadults&quot;</span>, <span class="st">&quot;adults&quot;</span>,<span class="st">&quot;total&quot;</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;blue&#39;</span>,<span class="st">&#39;orange&#39;</span>,<span class="st">&#39;red&#39;</span>,<span class="st">&#39;black&#39;</span>), <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="06-eigenvectors_files/figure-html/unnamed-chunk-15-1.png" width="672" />
Let’s run the iteration further. This time, we won’t display the table (gets too big), and we will just show the plot of 100 iterations</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.18</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">71</span>),<span class="fu">c</span>(<span class="fl">0.33</span>,<span class="dv">0</span>,<span class="fl">0.94</span>)) <span class="co"># the population dynamics matrix</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>x0 <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">76</span>,<span class="dv">502</span>) <span class="co"># the inital value</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">100</span>  <span class="co"># iterate N=10 times</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="at">nrow=</span><span class="fu">nrow</span>(A),<span class="at">ncol=</span>N<span class="sc">+</span><span class="dv">1</span>) <span class="co"># initialize an all 0 matrix to store values in</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>X[,<span class="dv">1</span>] <span class="ot">=</span> x0 <span class="co"># the first column is the initial population</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(N<span class="sc">+</span><span class="dv">1</span>)) {  <span class="co"># loopn from 2 to N+1</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  X[,i] <span class="ot">=</span> A <span class="sc">%*%</span> X[,i<span class="dv">-1</span>] <span class="co"># Apply A to column i-1 and put the value in column i</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>tot <span class="ot">=</span> X[<span class="dv">1</span>,] <span class="sc">+</span> X[<span class="dv">2</span>,] <span class="sc">+</span> X[<span class="dv">3</span>,]</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,N<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t,X[<span class="dv">1</span>,],<span class="at">type=</span><span class="st">&#39;l&#39;</span>,<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1000</span>),<span class="at">ylab=</span><span class="st">&quot;population&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;year&quot;</span>,<span class="at">main=</span><span class="st">&quot;Spotted Owl Population&quot;</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">1</span>,],<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">8</span>, <span class="dv">1050</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;juvenile&quot;</span>, <span class="st">&quot;subadults&quot;</span>, <span class="st">&quot;adults&quot;</span>,<span class="st">&quot;total&quot;</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;blue&#39;</span>,<span class="st">&#39;orange&#39;</span>,<span class="st">&#39;red&#39;</span>,<span class="st">&#39;black&#39;</span>), <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="06-eigenvectors_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>They do seem to be dying out.</p>
</div>
<div id="eigenanalysis" class="section level3" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Eigenanalysis</h3>
<p>Now we check the eigenvectors and eigenvalues to see if they help us understand what is going on.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  0.9835927+0.0000000i -0.0217964+0.2059185i -0.0217964-0.2059185i
## 
## $vectors
##               [,1]                  [,2]                  [,3]
## [1,] 0.31754239+0i  0.6820937+0.0000000i  0.6820937+0.0000000i
## [2,] 0.05811107+0i -0.0624124-0.5896338i -0.0624124+0.5896338i
## [3,] 0.94646180+0i -0.0450520+0.4256233i -0.0450520-0.4256233i</code></pre>
<p>The first eigenvalue is <span class="math inline">\(\lambda_1 = 0.98\)</span>, and the other two are complex. R always lists the eigenvalues from largest to smallest, so in this case the largets eigenvalue is less than one. That means that in that direction, the population is dying off by 2% each year.</p>
<p>If we extract the corresponding eigenvector, and scale it to sum to 1, we get</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">=</span> <span class="fu">eigen</span>(A)<span class="sc">$</span>vectors[,<span class="dv">1</span>] <span class="co"># get the first eigenvector</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">=</span> <span class="fu">Re</span>(v1) <span class="co"># drop the imaginary part</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>v1<span class="sc">/</span><span class="fu">sum</span>(v1)  <span class="co"># scale it to sum to 1</span></span></code></pre></div>
<pre><code>## [1] 0.24017754 0.04395311 0.71586935</code></pre>
<p>What this is telling us that as the population dies off, it does so in this eigenvector direction with 24.0% of the population being juveniles, 4.4% subadults, and 71.5% adults.</p>
<p>The owls were going extinct because of the logging in the Pacific Northwest. Suppose that we make the case that by stopping logging we will increase the survival rate from juvenile to subadult from 0.18 to 0.26 (by improving the habititat the juvinile owls have a better chance of surviving the first year). In this case, the eigenvalues and eigenvectors becomes:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.26</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">71</span>),<span class="fu">c</span>(<span class="fl">0.33</span>,<span class="dv">0</span>,<span class="fl">0.94</span>))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  1.0008184+0.0000000i -0.0304092+0.2448335i -0.0304092-0.2448335i
## 
## $vectors
##              [,1]                  [,2]                  [,3]
## [1,] 0.3121152+0i -0.0754384+0.6073766i -0.0754384-0.6073766i
## [2,] 0.0810836+0i  0.6450012+0.0000000i  0.6450012+0.0000000i
## [3,] 0.9465778+0i -0.4436732-0.1119384i -0.4436732+0.1119384i</code></pre>
<p>Notice that the largest eigenvalue now becomes 1. And if we iterate, we see that the population does not die off (it even grows slightly).</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.26</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">71</span>),<span class="fu">c</span>(<span class="fl">0.33</span>,<span class="dv">0</span>,<span class="fl">0.94</span>)) <span class="co"># the population dynamics matrix</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>x0 <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">76</span>,<span class="dv">502</span>) <span class="co"># the inital value</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">100</span>  <span class="co"># iterate N=10 times</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="at">nrow=</span><span class="fu">nrow</span>(A),<span class="at">ncol=</span>N<span class="sc">+</span><span class="dv">1</span>) <span class="co"># initialize an all 0 matrix to store values in</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>X[,<span class="dv">1</span>] <span class="ot">=</span> x0 <span class="co"># the first column is the initial population</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(N<span class="sc">+</span><span class="dv">1</span>)) {  <span class="co"># loopn from 2 to N+1</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  X[,i] <span class="ot">=</span> A <span class="sc">%*%</span> X[,i<span class="dv">-1</span>] <span class="co"># Apply A to column i-1 and put the value in column i</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>tot <span class="ot">=</span> X[<span class="dv">1</span>,] <span class="sc">+</span> X[<span class="dv">2</span>,] <span class="sc">+</span> X[<span class="dv">3</span>,]</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,N<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t,X[<span class="dv">1</span>,],<span class="at">type=</span><span class="st">&#39;l&#39;</span>,<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1000</span>),<span class="at">ylab=</span><span class="st">&quot;population&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;year&quot;</span>,<span class="at">main=</span><span class="st">&quot;Spotted Owl Population&quot;</span>)</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">1</span>,],<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>)</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>)</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">8</span>, <span class="dv">1050</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;juvenile&quot;</span>, <span class="st">&quot;subadults&quot;</span>, <span class="st">&quot;adults&quot;</span>,<span class="st">&quot;total&quot;</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;blue&#39;</span>,<span class="st">&#39;orange&#39;</span>,<span class="st">&#39;red&#39;</span>,<span class="st">&#39;black&#39;</span>), <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="06-eigenvectors_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Finally, we go back to the original system, which is dying out, but start with a totally different age distribution. You can see the non-dominant eigevectors dying out quickly at the beginning and the dominant eigenvector, of eigenvalue 0.98, taking over.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.18</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">71</span>),<span class="fu">c</span>(<span class="fl">0.33</span>,<span class="dv">0</span>,<span class="fl">0.94</span>)) <span class="co"># the population dynamics matrix</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>x0 <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">70</span>,<span class="dv">600</span>,<span class="dv">8</span>) <span class="co"># the inital value</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">20</span>  <span class="co"># iterate N=100 times</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="at">nrow=</span><span class="fu">nrow</span>(A),<span class="at">ncol=</span>N<span class="sc">+</span><span class="dv">1</span>) <span class="co"># initialize an all 0 matrix to store values in</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>X[,<span class="dv">1</span>] <span class="ot">=</span> x0 <span class="co"># the first column is the initial population</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(N<span class="sc">+</span><span class="dv">1</span>)) {  <span class="co"># loopn from 2 to N+1</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  X[,i] <span class="ot">=</span> A <span class="sc">%*%</span> X[,i<span class="dv">-1</span>] <span class="co"># Apply A to column i-1 and put the value in column i</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>tot <span class="ot">=</span> X[<span class="dv">1</span>,] <span class="sc">+</span> X[<span class="dv">2</span>,] <span class="sc">+</span> X[<span class="dv">3</span>,]</span></code></pre></div>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,N<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(t,X[<span class="dv">1</span>,],<span class="at">type=</span><span class="st">&#39;l&#39;</span>,<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1000</span>),<span class="at">ylab=</span><span class="st">&quot;population&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;year&quot;</span>,<span class="at">main=</span><span class="st">&quot;Spotted Owl Population&quot;</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">1</span>,],<span class="at">col=</span><span class="st">&#39;blue&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">2</span>,],<span class="at">col=</span><span class="st">&#39;orange&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,X[<span class="dv">3</span>,],<span class="at">col=</span><span class="st">&#39;red&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(t,tot,<span class="at">col=</span><span class="st">&#39;black&#39;</span>)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">8</span>, <span class="dv">1050</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;juvenile&quot;</span>, <span class="st">&quot;subadults&quot;</span>, <span class="st">&quot;adults&quot;</span>,<span class="st">&quot;total&quot;</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;blue&#39;</span>,<span class="st">&#39;orange&#39;</span>,<span class="st">&#39;red&#39;</span>,<span class="st">&#39;black&#39;</span>), <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="06-eigenvectors_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>s</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
