
# Problem Set 3

* Due: **Wednesday** September 22 by midnight. 
     * Free Extension: anything turned in by 5PM Friday will be considered on time. 
     * After 5PM Friday, late assignments are subject to a 15% late penalty.
     * After I post the solution on Monday, there is a 50% late penalty.
* Upload your solutions to Moodle in a PDF. 
* Please feel free to **use RStudio for all row reductions.**
* You can download the [Rmd source file  for this problem set](https://github.com/Tom-Halverson/math236_f20/blob/main/PS3-problem-set-3.Rmd).

The Problem Set covers sections 1.7 Linear Independence and 1.8 Linear Transformations.

## RREF for a set of vectors

Suppose that we have five vectors 
$\mathsf{v}_1, \mathsf{v}_2,\mathsf{v}_3,\mathsf{v}_4,\mathsf{v}_5$ in $\mathbb{R}^4$ and that the matrix $A$ containing those vectors row reduces as follows
$$
A = \left[
\begin{array}{ccc}
\mid & \mid  & \mid & \mid & \mid \\
\mathsf{v}_1 & \mathsf{v}_2 & \mathsf{v}_3 &\mathsf{v}_4 &\mathsf{v}_5  \\
\mid & \mid  & \mid & \mid & \mid 
\end{array}
\right]
 \longrightarrow
\begin{bmatrix}
1 & 0 & -3 & 0 & 2  \\
0 & 1 & 4 & 0 &  1  \\
0 & 0 & 0 & 1 & 1  \\
0 & 0 & 0 & 0 & 0 
\end{bmatrix}.
$$


  a.  Do the vectors $\mathsf{v}_1, \mathsf{v}_2, \mathsf{v}_3, \mathsf{v}_4, \mathsf{v}_5$ span $\mathbb{R}^4$? Justify your answer.
  
  b. Give the solution, in parametric form, to the homogeneous system of equations $A x = 0$ for this problem.
  
  c. Give a dependence relation among the vectors $\mathsf{v_1}, \mathsf{v_2},\mathsf{v_3},\mathsf{v_4}, \mathsf{v_5}$.

  d. Is the vector $\mathsf{v}_3$  in $\mathrm{span}(\mathsf{v}_1,\mathsf{v}_2)$? Justify your answer.

  e. Suppose that $\mathsf{b} = 5 \mathsf{v}_1  + \mathsf{v}_2 - 3 \mathsf{v}_3 +4 \mathsf{v}_4 - \mathsf{v}_5$. Use what you have done above to write $\mathsf{b}$ as a different linear combination  of $\mathsf{v_1}, \mathsf{v_2},\mathsf{v_3},\mathsf{v_4}, \mathsf{v_5}$ (i.e., with different weights).


## Linear independence and unique expressions.

It is an important fact that if a set of vectors $\mathsf{v}_1, \mathsf{v}_2, \mathsf{v}_3, \ldots, \mathsf{v}_n$ is *linearly independent* then any vector in the span of these vectors can be written as a *unique* linear combination of those vectors. 

a. This property has a fairly simple proof. Let's suppose that n = 4 for simplicity and that a vector v can be written in two ways as a combination of those vectors:
$$
\begin{array}{ccccccc}
v &=& c_1 \mathsf{v}_1 &+&  c_2 \mathsf{v}_2 &+&  c_3 \mathsf{v}_3 &+&  c_4 \mathsf{v}_4 \\
&=& d_1 \mathsf{v}_1 &+&  d_2 \mathsf{v}_2 &+&  d_3 \mathsf{v}_3 &+&  d_4 \mathsf{v}_4
\end{array}
$$
Then use the definition of linear independence to prove that $c_1 = d_1$, $c_2 = d_2$, $c_3 = d_3$, and $c_4 = d_4$.


## Is the transformation linear?
There are three transformations below. If you believe that the transformation is linear, then show it is by showing that the three linear transformation rules apply for *arbitrary* vectors. If you believe that the transformation is not linear. Then show that one of the rules fails for *specific* vectors.

(a)
$$
T \left( \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} \right)
=
\begin{bmatrix} x_1 + x_2 + x_3 -1 \\ x_1 - x_2 + x_3 + 1  \end{bmatrix}
$$

(b)
$$
T \left( \begin{bmatrix} x_1 \\ x_2  \end{bmatrix} \right)
=
\begin{bmatrix} 3 x_1 - 5 x_2 \\ 2 x_1 + x_2 \\ 2 x_1 + 3 x_2 \end{bmatrix}
$$
(c)
$$
T \left( \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} \right)
=
\begin{bmatrix} x_1 + x_2^2 + x_3 \\ 2 x_2 + x_1 x_3 \\ 2 x_1 + 3 x_2 + x_3 \end{bmatrix}
$$

## Partial Information about a Linear Transformation

We are given that $T: \mathbb{R}^4 \rightarrow \mathbb{R}^3$ is a linear transformation such that: 
$$
T\left(\begin{bmatrix} 3 \\ ~2~ \\ 1 \\ 2 \end{bmatrix} \right)=\begin{bmatrix}  ~2~ \\ 3 \\ 6 \end{bmatrix}
\qquad\hbox{and}\qquad
T\left(\begin{bmatrix}~~2 \\ -1 \\ 0 \\ -1 \end{bmatrix} \right)=\begin{bmatrix} 2 \\ ~0~  \\ 1 \end{bmatrix}.
$$
Use this information to compute the value of $T$ below? 
$$T\left(\begin{bmatrix} 5 \\ 8 \\ ~3~ \\ 8 \end{bmatrix} \right) = \hskip5in$$
Hint: express the third input vector as a linear combination of the first two.

## Square, Wide, and Tall Matrices

In each question below, choose all of the answers that apply, and give a succinct explanation of how you know that it is true. 

1. [Wide] You are given a wide 5 x 8 matrix and you are studying the matrix equation $A x = b$. These problems are said to be **under constrained** because there are fewer equations (constraints) than variables. 
$$
A=\begin{bmatrix} 
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\end{bmatrix}
$$

     (a) The vector that you are trying to get to is $b \in \mathbb{R}^m$ and the solution vectors are $x \in \mathbb{R}^n$. What are $m$ and $n$?
     (a) Decide which of the following statements are true and give a short and succinct justification of your answer using complete sentences and good punctuation. 
          i. The columns of $A$ must span $\mathbb{R}^m$.
          i. The columns of $A$ must be linearly dependent.
          i. There is a unique solution to $A x = 0$.
          i. If the columns span $\mathbb{R}^m$ then there is a unique solution to $A x = b$ for all $b$.

\

2. [Tall] You are given a wide 7 x 4 matrix and you are studying the matrix equation $A x = b$. These problems are said to be **over constrained** because there are more equations (constraints) than variables. 
$$
A=\begin{bmatrix} 
\ \cdot & \cdot & \cdot & \cdot \ \\
\ \cdot & \cdot & \cdot & \cdot \ \\
\ \cdot & \cdot & \cdot & \cdot \ \\
\ \cdot & \cdot & \cdot & \cdot \ \\
\ \cdot & \cdot & \cdot & \cdot \ \\
\ \cdot & \cdot & \cdot & \cdot \ \\
\ \cdot & \cdot & \cdot & \cdot \ \\
\end{bmatrix}
$$

     (a) The vector that you are trying to get to is $b \in \mathbb{R}^m$ and the solution vectors are $x \in \mathbb{R}^n$. What are $m$ and $n$?
     (a) Decide which of the following statements are true and give a short and succinct justification of your answer using complete sentences and good punctuation. 
          i. The columns of $A$ might span $\mathbb{R}^m$.
          i. The columns of $A$ must be linearly dependent.
          i. There is a unique solution to $A x = 0$.

\

3. [Square] You are given a square 6 x 6 matrix and you are studying the matrix equation $A x = b$.
$$
A=\begin{bmatrix} 
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\  \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\  \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\  \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\  \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\ \cdot & \cdot & \cdot & \cdot & \cdot & \cdot\ \\
\end{bmatrix}
$$

     (a) The vector that you are trying to get to is $b \in \mathbb{R}^m$ and the solution vectors are $x \in \mathbb{R}^n$. What are $m$ and $n$?
     (a) Decide which of the following statements are true and give a short and succinct justification of your answer using complete sentences and good punctuation. 
          i. The columns of $A$ must span $\mathbb{R}^m$.
          iii. If the columns span $\mathbb{R}^m$ then there is a unique solution to $A x = b$ for all $b$.
          iv. If ${\bf 0}$ is the only solution to $A x = {\bf 0}$, then there is a unique solution to $A x = b$ for all $b \in \mathbb{R}^m$.
          v. The columns of $A$ span $\mathbb{R}^m$ if and only if the columns of $A$ are linearly independent.







