<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 1 SVD and Image Compression | 12-image-compression.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 1 SVD and Image Compression | 12-image-compression.knit" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 1 SVD and Image Compression | 12-image-compression.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>


<link rel="stylesheet" href="m236.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">MATH 236: Linear Algebra</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#svd-and-image-compression"><i class="fa fa-check"></i><b>1</b> SVD and Image Compression</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#singular-value-decomposition"><i class="fa fa-check"></i><b>1.1</b> Singular Value Decomposition</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path=""><a href="#svd-of-a-wide-matrix"><i class="fa fa-check"></i><b>1.1.1</b> SVD of a Wide Matrix</a></li>
<li class="chapter" data-level="1.1.2" data-path=""><a href="#your-turn-svd-of-a-square-matrix"><i class="fa fa-check"></i><b>1.1.2</b> Your Turn: SVD of a Square Matrix</a></li>
<li class="chapter" data-level="1.1.3" data-path=""><a href="#your-turn-svd-of-a-tall-matrix"><i class="fa fa-check"></i><b>1.1.3</b> Your Turn: SVD of a Tall Matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#image-compression"><i class="fa fa-check"></i><b>1.2</b> Image Compression</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path=""><a href="#converting-a-jpeg-image-into-a-matrix"><i class="fa fa-check"></i><b>1.2.1</b> Converting a JPEG image into a Matrix</a></li>
<li class="chapter" data-level="1.2.2" data-path=""><a href="#svd-of-a-raster-image"><i class="fa fa-check"></i><b>1.2.2</b> SVD of a Raster Image</a></li>
<li class="chapter" data-level="1.2.3" data-path=""><a href="#svd-approximation-of-the-image"><i class="fa fa-check"></i><b>1.2.3</b> SVD Approximation of the Image</a></li>
<li class="chapter" data-level="1.2.4" data-path=""><a href="#svd-of-a-lighthouse"><i class="fa fa-check"></i><b>1.2.4</b> SVD of a Lighthouse</a></li>
<li class="chapter" data-level="1.2.5" data-path=""><a href="#your-turn"><i class="fa fa-check"></i><b>1.2.5</b> Your Turn</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:title:end-->
<!--bookdown:title:start-->
<div id="svd-and-image-compression" class="section level1" number="1">
<h1><span class="header-section-number">Section 1</span> SVD and Image Compression</h1>
<p><a href="https://github.com/mathbeveridge/math236_f20/blob/main/12-image-compression.Rmd">Download this Rmd file</a></p>
<p>Today we will use the <code>svd</code> command to find the Singular Value Decomposition of an <span class="math inline">\(m \times n\)</span> matrix.
We will practice reading the output of this command and finding bases for the four fundamental subspaces of a matrix.
Then we will look at a cool application of SVD: image compression!</p>
<center>
<img src="https://raw.githubusercontent.com/mathbeveridge/math236_f20/main/images/svd-summary.png" style="width:100.0%" />
</center>
<div id="singular-value-decomposition" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Singular Value Decomposition</h2>
<p>Let’s start by looking at the SVD for a couple of matrices. For each one:</p>
<ol style="list-style-type: lower-alpha">
<li>Determine the rank of <span class="math inline">\(A\)</span></li>
<li>Identify the basis for each of the four fundamental subspaces
<span class="math display">\[
\mbox{Nul}(A), \qquad \mbox{Col}(A), \qquad \mbox{Row}(A), \qquad \mbox{Nul}(A^{\top}).
\]</span></li>
<li>Pick a vector <span class="math inline">\(\mathsf{x}\)</span> from the basis for <span class="math inline">\(\mbox{Nul}(A)\)</span> and confirm that <span class="math inline">\(A \mathsf{x} = \mathbf{0}\)</span>.</li>
<li>Pick a vector <span class="math inline">\(\mathsf{y}\)</span> from the basis for <span class="math inline">\(\mbox{Col}(A)\)</span> and confirm that <span class="math inline">\(\mathsf{y}\)</span> can be written as the a linear combination of the columns of <span class="math inline">\(A\)</span>.</li>
<li>Find the spectral decomposition of <span class="math inline">\(A\)</span></li>
<li>Use the spectral decomposition to create approximations of matrix <span class="math inline">\(A\)</span> and then compare the quality of the approximation to the size of the gaps of the singular values.</li>
</ol>
<div id="svd-of-a-wide-matrix" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> SVD of a Wide Matrix</h3>
<p>Here is a <span class="math inline">\(4 \times 5\)</span> matrix <span class="math inline">\(A\)</span>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">A =</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">2</span>),<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">5</span>,<span class="sc">-</span><span class="dv">4</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1   -2    1    0    1
## [2,]   -1    3   -1    1   -1
## [3,]    1    0    1    4    5
## [4,]    0    2    0    0   -4</code></pre>
<p>Let’s call <code>svd(A)</code> and see what we get.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">decomp =</span> <span class="fu">svd</span>(A))</span></code></pre></div>
<pre><code>## $d
## [1] 7.657063e+00 4.528454e+00 1.965323e+00 1.981025e-16
## 
## $u
##            [,1]       [,2]       [,3]       [,4]
## [1,] -0.2248593  0.3962930 -0.4593417 -0.7624929
## [2,]  0.2098332 -0.7003225  0.3056557 -0.6099943
## [3,] -0.8000554 -0.5005874 -0.2933731  0.1524986
## [4,]  0.5150919 -0.3192373 -0.7807125  0.1524986
## 
## $v
##            [,1]        [,2]       [,3]       [,4]
## [1,] -0.1612561  0.13161844 -0.5385224  0.1709288
## [2,]  0.2754845 -0.77996334  0.1395320 -0.4039829
## [3,] -0.1612561  0.13161844 -0.5385224 -0.7769031
## [4,] -0.3905399 -0.59682006 -0.4415746  0.4039829
## [5,] -0.8482805 -0.02856877  0.4533541 -0.2019914</code></pre>
<p>The return value has three attributes:</p>
<ul>
<li><code>decomp$d</code>: these are the singular values <span class="math inline">\(\sigma_1, \sigma_2, \sigma_3, \sigma_4\)</span>. Note that <span class="math inline">\(\sigma_4=0\)</span>.</li>
<li><code>decomp$u</code>: the <span class="math inline">\(4 \times 4\)</span> matrix whose columns are the left singular vectors <span class="math inline">\(\mathsf{u}_1, \mathsf{u}_1, \mathsf{u}_1, \mathsf{u}_1\)</span> corresponding to the singular values.</li>
<li><code>decomp$v</code>: the <span class="math inline">\(5 \times 4\)</span> matrix whose columns are right singular vectors the right singular vectors <span class="math inline">\(\mathsf{v}_1, \mathsf{v}_2, \mathsf{v}_3, \mathsf{v}_4\)</span> corresponding to the singular values. The final vector <span class="math inline">\(\mathsf{v}_5\)</span> is missing!</li>
</ul>
<p><strong>Note:</strong> The columns of the matrix <code>decomp$v$</code> are singular vectors (not the rows).</p>
<p><strong>Warning!</strong> We were expecting <code>decomp$v</code> to be a <span class="math inline">\(5 \times 5\)</span> matrix, and R only returned a <span class="math inline">\(5 \times 4\)</span> matrix. What is wrong!? The missing column is the final orthonormal vector <span class="math inline">\(\mathsf{v}_5\)</span> from <span class="math inline">\(\mbox{Nul}(A)\)</span>.</p>
<div id="why-has-r-omitted-this-vector" class="section level4" number="1.1.1.1">
<h4><span class="header-section-number">1.1.1.1</span> Why has R Omitted this Vector?</h4>
<p>The answer is that <strong>RStudio is being efficient.</strong> R has omitted vector <span class="math inline">\(\mathsf{v}_5\)</span> because we do not need this vector to create the spectral decomposition of <span class="math inline">\(A\)</span>. That spectral decomposition is
<span class="math display">\[
A = \sigma_1 \mathsf{u}_1 \mathsf{v}_1^{\top} + \sigma_2 \mathsf{u}_2 \mathsf{v}_2^{\top} +  \sigma_3 \mathsf{u}_3 \mathsf{v}_3^{\top} +  \sigma_4 \mathsf{u}_4 \mathsf{v}_4^{\top}.
\]</span>
Note that we do not use the vector <span class="math inline">\(\mathsf{v}_5\)</span>. So R didn’t calculate it for us (to save computation time). If <span class="math inline">\(A\)</span> had been a <span class="math inline">\(10 \times 4\)</span> matrix, this would be a pretty good idea: why find 6 vectors that we don’t need?</p>
<p>And don’t worry: we can easily extend the columns of <code>decomp$u</code> into an orthonormal basis for <span class="math inline">\(\mathbb{R}^5\)</span>. One simple way is to find a basis for the orthogonal complement of <span class="math inline">\(\mbox{span}(\mathsf{v}_1\mathsf{v}_2,\mathsf{v}_3,\mathsf{v}_4)\)</span>. We could do this by manually by finding an orthogonal basis for the nullspace of <code>t(decomp$v)</code>.</p>
<p>If you take MATH 365 Computational Linear Algebra, you will learn more about the <span class="math inline">\(QR\)</span>-decomposition. That gives a fast way to fill in the missing vectors if you need them.</p>
<p><strong>Pro Tip:</strong> When you use <code>svd</code> on a rectangular matrix, just remember that some of the singular vectors are missing.</p>
<ul>
<li>If <span class="math inline">\(m &gt; n\)</span> then there are <span class="math inline">\(m-n\)</span> missing columns of <span class="math inline">\(U\)</span>, all lying in <span class="math inline">\(\mbox{Nul}(A^{\top})\)</span>.</li>
<li>If <span class="math inline">\(n &gt; m\)</span> then there are <span class="math inline">\(n-m\)</span> missing columns of <span class="math inline">\(V\)</span>, all lying in <span class="math inline">\(\mbox{Nul(A)}\)</span>.</li>
</ul>
</div>
<div id="the-four-fundamental-subspaces-of-a" class="section level4" number="1.1.1.2">
<h4><span class="header-section-number">1.1.1.2</span> The Four Fundamental Subspaces of <span class="math inline">\(A\)</span></h4>
<p>Keeping this is mind, let’s characterize the four fundamental subspaces of our example <span class="math inline">\(5 \times 4\)</span> matrix <span class="math inline">\(A.\)</span></p>
<ul>
<li>The matrix <span class="math inline">\(A\)</span> has rank <span class="math inline">\(3\)</span> because there are three nonzero signular values.</li>
<li><span class="math inline">\(\mbox{Row}(A)\)</span> is 3-dimensional with basis <code>decomp$v[,1:3]</code></li>
<li><span class="math inline">\(\mbox{Nul}(A)\)</span> is 2-dimensional because <span class="math inline">\(\sigma_4=0\)</span> and there is <span class="math inline">\(5-4=1\)</span> missing left right singular vector. We can use <code>decomp$v[,4]</code> as one basis vector. We can find the remaining <span class="math inline">\(5-4=1\)</span> vector by finding the nullspace of <code>t(decomp$v)</code>.</li>
<li><span class="math inline">\(\mbox{Col}(A)\)</span> is 3-dimensional with basis <code>decomp$u[,1:3]</code></li>
<li><span class="math inline">\(\mbox{Nul}(A^{\top})\)</span> is 1-dimensional. The vector <code>decomp$u[,4]</code> is a basis.</li>
</ul>
</div>
</div>
<div id="your-turn-svd-of-a-square-matrix" class="section level3" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Your Turn: SVD of a Square Matrix</h3>
<p>Characterize the four subspaces of this <span class="math inline">\(5x5\)</span> matrix. Note that since <span class="math inline">\(A\)</span> is square, the matrices <span class="math inline">\(U\)</span> and <span class="math inline">\(V\)</span> will both contain a full basis for <span class="math inline">\(\mathbb{R}^5\)</span>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">A =</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">5</span>,<span class="sc">-</span><span class="dv">3</span>,<span class="dv">6</span>,<span class="sc">-</span><span class="dv">1</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">2</span>,<span class="sc">-</span><span class="dv">4</span>),<span class="fu">c</span>(<span class="dv">9</span>,<span class="sc">-</span><span class="dv">4</span>,<span class="dv">9</span>,<span class="sc">-</span><span class="dv">18</span>,<span class="dv">14</span>),<span class="fu">c</span>(<span class="dv">3</span>,<span class="sc">-</span><span class="dv">4</span>,<span class="dv">3</span>,<span class="sc">-</span><span class="dv">6</span>,<span class="dv">3</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">11</span>,<span class="sc">-</span><span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">11</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]   -3   -1    9    3   -2
## [2,]    5   -2   -4   -4   11
## [3,]   -3   -1    9    3   -2
## [4,]    6    2  -18   -6    4
## [5,]   -1   -4   14    3   11</code></pre>
</div>
<div id="your-turn-svd-of-a-tall-matrix" class="section level3" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Your Turn: SVD of a Tall Matrix</h3>
<p>Characterize the four subspaces of this <span class="math inline">\(6x4\)</span> matrix. This time around, we will be missing <span class="math inline">\(6-4=2\)</span> of the left singular vectors that we need to extend `svd(A)<span class="math inline">\(u\)</span> into a basis of <span class="math inline">\(\mathbb{R}^6\)</span>. These two singular vectors complete the basis for <span class="math inline">\(\mbox{Nul(A^{\top})}\)</span>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">A =</span> <span class="fu">cbind</span>(x<span class="sc">^</span><span class="dv">0</span>, x<span class="sc">^</span><span class="dv">1</span>, x<span class="sc">^</span><span class="dv">2</span>, x<span class="sc">^</span><span class="dv">3</span>))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    1    1    1
## [2,]    1    2    4    8
## [3,]    1    3    9   27
## [4,]    1    4   16   64
## [5,]    1    5   25  125
## [6,]    1    6   36  216</code></pre>
</div>
</div>
<div id="image-compression" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Image Compression</h2>
<div id="converting-a-jpeg-image-into-a-matrix" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Converting a JPEG image into a Matrix</h3>
<p>You may need to install the <code>jpeg</code> and <code>raster</code> packages. Let’s find out.</p>
<ul>
<li>Click on the ‘Packages’ tab in the lower right window</li>
<li>Either search or scroll to see if the the <code>jpeg</code> and <code>raster</code> are there.</li>
<li>If so, then click the checkbox to load the package into memory.
If the package is missing, then uncomment and run the folllowing code chunk</li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&#39;jpeg&#39;)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&#39;raster&#39;)</span></span></code></pre></div>
<p>You’ve probably heard of JPEG image files. The <code>jpeg</code> package will allow us to import those images into R. The JPEG format uses image compression. So we need to turn them into a <strong>raster (bitmap) image</strong> which is a rectangular grid of pixels or dots. In other words a raster image is a matrix. The package <code>raster</code> will do this conversion for us.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jpeg)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster)</span></code></pre></div>
<p>The following defines two helper functions</p>
<ul>
<li><code>get_image(filename)</code> reads in a JPEG file and convert it into a raster image.</li>
<li><code>plot_image(img)</code> creates a plot of the raster image</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># converts a JPEG file into a raster image (a numerical matrix)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># if the JPEG is a color image, it is converted to black and white.</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>get_image <span class="ot">&lt;-</span> <span class="cf">function</span>(filename) {</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># read the jpeg file</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  img <span class="ot">=</span> <span class="fu">readJPEG</span>(<span class="fu">readBin</span>(filename,<span class="st">&quot;raw&quot;</span>,<span class="fl">1e6</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  img.dim <span class="ot">=</span> <span class="fu">dim</span>(img)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># if this is a color image, we need to turn it into a grayscale image</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  img <span class="ot">=</span> img[,,<span class="dv">1</span>]<span class="sc">+</span>img[,,<span class="dv">2</span>]<span class="sc">+</span>img[,,<span class="dv">3</span>]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  img <span class="ot">&lt;-</span> img<span class="sc">/</span><span class="fu">max</span>(img)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  img.dim <span class="ot">=</span> <span class="fu">dim</span>(img)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (img)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>plot_image <span class="ot">=</span> <span class="cf">function</span>(img,...) {</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">type=</span><span class="st">&#39;n&#39;</span>,<span class="at">xlab=</span><span class="st">&quot; &quot;</span>,<span class="at">ylab=</span> <span class="st">&quot; &quot;</span>,...)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rasterImage</span>(img, <span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">2.0</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Let start by reading in a picture of a tartan.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>where.tartan <span class="ot">=</span> <span class="st">&quot;https://upload.wikimedia.org/wikipedia/commons/e/ec/Burberry.jpg&quot;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>img <span class="ot">=</span> <span class="fu">get_image</span>(where.tartan)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot_image(img,main=&quot;Image&quot;)</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(img)</span></code></pre></div>
<pre><code>## [1] 335 333</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dim</span>(img)) <span class="co"># prod(vec) = product of the entries of vec</span></span></code></pre></div>
<pre><code>## [1] 111555</code></pre>
<p>Each entry of <code>img</code> is a value in <span class="math inline">\([0,1]\)</span>. This is the <strong>grayscale value</strong> of a single pixel: value 0 corresponds to white and value 1 corresponds to black. The matrix <code>img</code> is a <span class="math inline">\(335 \times 333\)</span> matrix. So to store the image, we need to store <span class="math inline">\(111,555\)</span> floating point numbers (!). You can see compression methods are essential in practice.</p>
</div>
<div id="svd-of-a-raster-image" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> SVD of a Raster Image</h3>
<p>The <code>img</code> variable is just a matrix. So we can find its singular value decomposition. We find that there are some large gaps in the singular values.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>decomp <span class="ot">=</span><span class="fu">svd</span>(img)<span class="sc">$</span>d</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(decomp,pch=19,cex=.5,col=&#39;blue&#39;)</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(decomp,pch=19,cex=.5,col=&#39;blue&#39;,ylim=c(0,5))</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>decomp[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] 243.100715  23.459676  23.070452  22.687676  22.469706  11.317300
##  [7]   1.732057   1.647588   1.195523   1.161641</code></pre>
</div>
<div id="svd-approximation-of-the-image" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> SVD Approximation of the Image</h3>
<p>Now let’s create an SVD approximation of the image. Here is some helper code for us to use. The functions that you will call are</p>
<ul>
<li><code>plot_svd_approx(img, k)</code>: create the spectral decomposition corresponding to the <span class="math inline">\(k\)</span> largest singular values in the spectral decomposition.</li>
<li><code>get_svd_approx_error(img, k)</code>: reports the average pixel error of the approximation.</li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># returns the spectral decomposition matrix for the first k singular values</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>svd_approx <span class="ot">=</span> <span class="cf">function</span>(A,<span class="at">k =</span> <span class="fu">floor</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span><span class="sc">*</span><span class="fu">min</span>(<span class="fu">nrow</span>(A),<span class="fu">ncol</span>(A)))) {</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  decomp <span class="ot">=</span> <span class="fu">svd</span>(A)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  sings <span class="ot">=</span> decomp<span class="sc">$</span>d</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  U <span class="ot">=</span> decomp<span class="sc">$</span>u</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  V <span class="ot">=</span> decomp<span class="sc">$</span>v</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(k<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    D<span class="ot">=</span><span class="fu">matrix</span>(sings[<span class="dv">1</span>],<span class="at">nrow=</span><span class="dv">1</span>,<span class="at">ncol=</span><span class="dv">1</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    D<span class="ot">=</span><span class="fu">diag</span>(sings[<span class="dv">1</span><span class="sc">:</span>k])</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  M<span class="ot">=</span>U[,<span class="dv">1</span><span class="sc">:</span>k]<span class="sc">%*%</span>D<span class="sc">%*%</span><span class="fu">t</span>(V[,<span class="dv">1</span><span class="sc">:</span>k])</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(M)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># gets the svd approximation of the image</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>get_svd_approx_img <span class="ot">&lt;-</span> <span class="cf">function</span>(img,k) {</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  approxIm <span class="ot">=</span> <span class="fu">svd_approx</span>(img,k)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  approxIm[approxIm<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  approxIm[approxIm<span class="sc">&gt;</span><span class="dv">1</span>] <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (approxIm)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="co"># returns the average pixel error for the svd approximation of the image</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>get_svd_approx_error <span class="ot">&lt;-</span>  <span class="cf">function</span>(img, k) {</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>  approxImg <span class="ot">=</span> <span class="fu">get_svd_approx_img</span>(img,k)</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>  return  <span class="ot">=</span> <span class="fu">mean</span>(<span class="fu">abs</span>(img <span class="sc">-</span> approxImg))</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="co"># plots the SVD approximation of the image</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>plot_svd_approx<span class="ot">=</span><span class="cf">function</span>(img,k){</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>  approxIm <span class="ot">=</span> <span class="fu">get_svd_approx_img</span>(img,k)</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">type=</span><span class="st">&#39;n&#39;</span>)</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rasterImage</span>(approxIm, <span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">2.0</span>)</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>And here we show the singular value approximation with increasing numbers of singular values:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot_svd_approx(img,1)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_svd_approx_error</span>(img,<span class="dv">1</span>)</span></code></pre></div>
</div>
<div id="svd-of-a-lighthouse" class="section level3" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> SVD of a Lighthouse</h3>
<p>Now let’s see how SVD does with this picture of a lighthouse. Use the appropriate code above to explore the SVD approximations of this lighthouse. How big must <span class="math inline">\(k\)</span> be in order to get an okay approximation? to get an approximation that you can’t distinguish from the original?</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>where.lighthouse  <span class="ot">=</span> <span class="st">&quot;https://images.unsplash.com/6/lighthouse.jpg&quot;</span></span></code></pre></div>
</div>
<div id="your-turn" class="section level3" number="1.2.5">
<h3><span class="header-section-number">1.2.5</span> Your Turn</h3>
<p>Here are some JPEG files available on the web for you to try. Or you can use an image of your own choice! Have fun!</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># some jpeg images available on the web</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>where.cameraman <span class="ot">=</span> <span class="st">&quot;https://www.macalester.edu/~dshuman1/data/cameraman_small.jpg&quot;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>where.tiger <span class="ot">=</span> <span class="st">&quot;https://i.pinimg.com/originals/f2/b5/0b/f2b50b1cbdb7cd16fef50f5641d41e77.jpg&quot;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>where.flower<span class="ot">=</span> <span class="st">&quot;https://www.amylamb.com/wp-content/uploads/2013/04/Gerbera-320x320.jpg&quot;</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>where.pattern  <span class="ot">=</span> <span class="st">&quot;https://previews.123rf.com/images/noppanun/noppanun1411/noppanun141100046/33287656-black-and-white-geometric-seamless-pattern-with-triangle-and-trapezoid-abstract-background-vector-ep.jpg&quot;</span></span></code></pre></div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
