<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 20 Exam 3 Review | MATH 236: Linear Algebra</title>
  <meta name="description" content="This is the class activity manual for MATH 236 at Macalester College." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 20 Exam 3 Review | MATH 236: Linear Algebra" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the class activity manual for MATH 236 at Macalester College." />
  <meta name="github-repo" content="Tom-Halverson/math236_f21" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 20 Exam 3 Review | MATH 236: Linear Algebra" />
  
  <meta name="twitter:description" content="This is the class activity manual for MATH 236 at Macalester College." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exam-2-review.html"/>

<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>


<link rel="stylesheet" href="m236.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">MATH 236: Linear Algebra</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>I Problem Sets</b></span></li>
<li class="chapter" data-level="1" data-path="problem-set-1.html"><a href="problem-set-1.html"><i class="fa fa-check"></i><b>1</b> Problem Set 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="problem-set-1.html"><a href="problem-set-1.html#characterize-the-solution-set"><i class="fa fa-check"></i><b>1.1</b> Characterize the Solution Set</a></li>
<li class="chapter" data-level="1.2" data-path="problem-set-1.html"><a href="problem-set-1.html#find-the-general-solution"><i class="fa fa-check"></i><b>1.2</b> Find the General Solution</a></li>
<li class="chapter" data-level="1.3" data-path="problem-set-1.html"><a href="problem-set-1.html#elementary-row-operations-are-reversible"><i class="fa fa-check"></i><b>1.3</b> Elementary row operations are reversible</a></li>
<li class="chapter" data-level="1.4" data-path="problem-set-1.html"><a href="problem-set-1.html#designer-parabolas"><i class="fa fa-check"></i><b>1.4</b> Designer Parabolas</a></li>
<li class="chapter" data-level="1.5" data-path="problem-set-1.html"><a href="problem-set-1.html#traffic-flow"><i class="fa fa-check"></i><b>1.5</b> Traffic Flow</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="problem-set-2.html"><a href="problem-set-2.html"><i class="fa fa-check"></i><b>2</b> Problem Set 2</a>
<ul>
<li class="chapter" data-level="2.1" data-path="problem-set-2.html"><a href="problem-set-2.html#vector-equation"><i class="fa fa-check"></i><b>2.1</b> Vector Equation</a></li>
<li class="chapter" data-level="2.2" data-path="problem-set-2.html"><a href="problem-set-2.html#matrix-equation"><i class="fa fa-check"></i><b>2.2</b> Matrix Equation</a></li>
<li class="chapter" data-level="2.3" data-path="problem-set-2.html"><a href="problem-set-2.html#rref-for-a-linear-system"><i class="fa fa-check"></i><b>2.3</b> RREF for a linear system</a></li>
<li class="chapter" data-level="2.4" data-path="problem-set-2.html"><a href="problem-set-2.html#a-square-matrix"><i class="fa fa-check"></i><b>2.4</b> A square matrix</a></li>
<li class="chapter" data-level="2.5" data-path="problem-set-2.html"><a href="problem-set-2.html#combining-solutions-to-a-mathsfx-mathsfb"><i class="fa fa-check"></i><b>2.5</b> Combining solutions to <span class="math inline">\(A \mathsf{x} = \mathsf{b}\)</span></a></li>
<li class="chapter" data-level="2.6" data-path="problem-set-2.html"><a href="problem-set-2.html#a-balanced-diet"><i class="fa fa-check"></i><b>2.6</b> A Balanced Diet</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="problem-set-3.html"><a href="problem-set-3.html"><i class="fa fa-check"></i><b>3</b> Problem Set 3</a>
<ul>
<li class="chapter" data-level="3.1" data-path="problem-set-3.html"><a href="problem-set-3.html#rref-for-a-set-of-vectors"><i class="fa fa-check"></i><b>3.1</b> RREF for a set of vectors</a></li>
<li class="chapter" data-level="3.2" data-path="problem-set-3.html"><a href="problem-set-3.html#linear-independence-and-unique-expressions."><i class="fa fa-check"></i><b>3.2</b> Linear independence and unique expressions.</a></li>
<li class="chapter" data-level="3.3" data-path="problem-set-3.html"><a href="problem-set-3.html#is-the-transformation-linear"><i class="fa fa-check"></i><b>3.3</b> Is the transformation linear?</a></li>
<li class="chapter" data-level="3.4" data-path="problem-set-3.html"><a href="problem-set-3.html#partial-information-about-a-linear-transformation"><i class="fa fa-check"></i><b>3.4</b> Partial Information about a Linear Transformation</a></li>
<li class="chapter" data-level="3.5" data-path="problem-set-3.html"><a href="problem-set-3.html#square-wide-and-tall-matrices"><i class="fa fa-check"></i><b>3.5</b> Square, Wide, and Tall Matrices</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="problem-set-4.html"><a href="problem-set-4.html"><i class="fa fa-check"></i><b>4</b> Problem Set 4</a>
<ul>
<li class="chapter" data-level="4.1" data-path="problem-set-4.html"><a href="problem-set-4.html#matrix-of-a-linear-transformation"><i class="fa fa-check"></i><b>4.1</b> Matrix of a Linear Transformation</a></li>
<li class="chapter" data-level="4.2" data-path="problem-set-4.html"><a href="problem-set-4.html#matrix-of-a-nonlinear-transformation"><i class="fa fa-check"></i><b>4.2</b> Matrix of a Nonlinear Transformation?</a></li>
<li class="chapter" data-level="4.3" data-path="problem-set-4.html"><a href="problem-set-4.html#inner-and-outer-products"><i class="fa fa-check"></i><b>4.3</b> Inner and Outer Products</a></li>
<li class="chapter" data-level="4.4" data-path="problem-set-4.html"><a href="problem-set-4.html#archaeological-seriation"><i class="fa fa-check"></i><b>4.4</b> Archaeological Seriation</a></li>
<li class="chapter" data-level="4.5" data-path="problem-set-4.html"><a href="problem-set-4.html#rental-car"><i class="fa fa-check"></i><b>4.5</b> Rental Car</a></li>
<li class="chapter" data-level="4.6" data-path="problem-set-4.html"><a href="problem-set-4.html#rainy-day-in-la"><i class="fa fa-check"></i><b>4.6</b> Rainy Day in LA</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="problem-set-5.html"><a href="problem-set-5.html"><i class="fa fa-check"></i><b>5</b> Problem Set 5</a>
<ul>
<li class="chapter" data-level="5.1" data-path="problem-set-5.html"><a href="problem-set-5.html#column-and-null-space"><i class="fa fa-check"></i><b>5.1</b> Column and Null Space</a></li>
<li class="chapter" data-level="5.2" data-path="problem-set-5.html"><a href="problem-set-5.html#vectors-rescaled"><i class="fa fa-check"></i><b>5.2</b> Vectors Rescaled</a></li>
<li class="chapter" data-level="5.3" data-path="problem-set-5.html"><a href="problem-set-5.html#fibonacci-vectors"><i class="fa fa-check"></i><b>5.3</b> Fibonacci Vectors</a></li>
<li class="chapter" data-level="5.4" data-path="problem-set-5.html"><a href="problem-set-5.html#a-vector-in-both-cola-and-nula"><i class="fa fa-check"></i><b>5.4</b> A Vector in Both Col(A) and Nul(A)</a></li>
<li class="chapter" data-level="5.5" data-path="problem-set-5.html"><a href="problem-set-5.html#getting-into-a-subspace"><i class="fa fa-check"></i><b>5.5</b> Getting Into a Subspace</a></li>
<li class="chapter" data-level="5.6" data-path="problem-set-5.html"><a href="problem-set-5.html#shrink-to-a-basis"><i class="fa fa-check"></i><b>5.6</b> Shrink to a basis</a></li>
<li class="chapter" data-level="5.7" data-path="problem-set-5.html"><a href="problem-set-5.html#extend-to-a-basis"><i class="fa fa-check"></i><b>5.7</b> Extend to a basis</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="problem-set-6.html"><a href="problem-set-6.html"><i class="fa fa-check"></i><b>6</b> Problem Set 6</a>
<ul>
<li class="chapter" data-level="6.1" data-path="problem-set-6.html"><a href="problem-set-6.html#dimension"><i class="fa fa-check"></i><b>6.1</b> Dimension</a></li>
<li class="chapter" data-level="6.2" data-path="problem-set-6.html"><a href="problem-set-6.html#a-tetrahedral-basis"><i class="fa fa-check"></i><b>6.2</b> A Tetrahedral Basis</a></li>
<li class="chapter" data-level="6.3" data-path="problem-set-6.html"><a href="problem-set-6.html#matrix-rank"><i class="fa fa-check"></i><b>6.3</b> Matrix Rank</a></li>
<li class="chapter" data-level="6.4" data-path="problem-set-6.html"><a href="problem-set-6.html#a-tale-of-two-bases"><i class="fa fa-check"></i><b>6.4</b> A Tale of Two Bases</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="problem-set-7.html"><a href="problem-set-7.html"><i class="fa fa-check"></i><b>7</b> Problem Set 7</a>
<ul>
<li class="chapter" data-level="7.1" data-path="problem-set-7.html"><a href="problem-set-7.html#rental-cars-revisited"><i class="fa fa-check"></i><b>7.1</b> Rental Cars Revisited</a></li>
<li class="chapter" data-level="7.2" data-path="problem-set-7.html"><a href="problem-set-7.html#diagonalization"><i class="fa fa-check"></i><b>7.2</b> Diagonalization</a></li>
<li class="chapter" data-level="7.3" data-path="problem-set-7.html"><a href="problem-set-7.html#same-eigenvectors"><i class="fa fa-check"></i><b>7.3</b> Same Eigenvectors</a></li>
<li class="chapter" data-level="7.4" data-path="problem-set-7.html"><a href="problem-set-7.html#rain-and-sunshine-revisited"><i class="fa fa-check"></i><b>7.4</b> Rain and Sunshine Revisited</a></li>
<li class="chapter" data-level="7.5" data-path="problem-set-7.html"><a href="problem-set-7.html#the-square-root-of-a-matrix"><i class="fa fa-check"></i><b>7.5</b> The Square Root of a Matrix?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="problem-set-8.html"><a href="problem-set-8.html"><i class="fa fa-check"></i><b>8</b> Problem Set 8</a>
<ul>
<li class="chapter" data-level="8.1" data-path="problem-set-8.html"><a href="problem-set-8.html#matrix-reconstruction"><i class="fa fa-check"></i><b>8.1</b> Matrix Reconstruction</a></li>
<li class="chapter" data-level="8.2" data-path="problem-set-8.html"><a href="problem-set-8.html#coyotes-and-roadrunners"><i class="fa fa-check"></i><b>8.2</b> Coyotes and Roadrunners</a></li>
<li class="chapter" data-level="8.3" data-path="problem-set-8.html"><a href="problem-set-8.html#hunt-creek"><i class="fa fa-check"></i><b>8.3</b> Hunt Creek</a></li>
<li class="chapter" data-level="8.4" data-path="problem-set-8.html"><a href="problem-set-8.html#halverson-numbers"><i class="fa fa-check"></i><b>8.4</b> Halverson Numbers</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="problem-set-9.html"><a href="problem-set-9.html"><i class="fa fa-check"></i><b>9</b> Problem Set 9</a>
<ul>
<li class="chapter" data-level="9.1" data-path="problem-set-9.html"><a href="problem-set-9.html#glucose-insulin"><i class="fa fa-check"></i><b>9.1</b> Glucose-Insulin</a></li>
<li class="chapter" data-level="9.2" data-path="problem-set-9.html"><a href="problem-set-9.html#the-rise-of-moscow"><i class="fa fa-check"></i><b>9.2</b> The Rise of Moscow</a></li>
<li class="chapter" data-level="9.3" data-path="problem-set-9.html"><a href="problem-set-9.html#orthogonal-complements"><i class="fa fa-check"></i><b>9.3</b> Orthogonal Complements</a></li>
</ul></li>
<li class="part"><span><b>II Concepts of Linear Algebra</b></span></li>
<li class="chapter" data-level="10" data-path="important-definitions.html"><a href="important-definitions.html"><i class="fa fa-check"></i><b>10</b> Important Definitions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="important-definitions.html"><a href="important-definitions.html#systems-of-equations"><i class="fa fa-check"></i><b>10.1</b> Systems of Equations</a></li>
<li class="chapter" data-level="10.2" data-path="important-definitions.html"><a href="important-definitions.html#linear-transformations"><i class="fa fa-check"></i><b>10.2</b> Linear Transformations</a></li>
<li class="chapter" data-level="10.3" data-path="important-definitions.html"><a href="important-definitions.html#vector-spaces"><i class="fa fa-check"></i><b>10.3</b> Vector Spaces</a></li>
<li class="chapter" data-level="10.4" data-path="important-definitions.html"><a href="important-definitions.html#matrices"><i class="fa fa-check"></i><b>10.4</b> Matrices</a></li>
</ul></li>
<li class="part"><span><b>III Linear Algebra in R</b></span></li>
<li class="chapter" data-level="11" data-path="class-examples.html"><a href="class-examples.html"><i class="fa fa-check"></i><b>11</b> Class Examples</a>
<ul>
<li class="chapter" data-level="11.1" data-path="class-examples.html"><a href="class-examples.html#day-3-wed-sep-8"><i class="fa fa-check"></i><b>11.1</b> Day 3: Wed Sep 8</a></li>
<li class="chapter" data-level="11.2" data-path="class-examples.html"><a href="class-examples.html#day-4-fri-sep-10"><i class="fa fa-check"></i><b>11.2</b> Day 4: Fri Sep 10</a></li>
<li class="chapter" data-level="11.3" data-path="class-examples.html"><a href="class-examples.html#day-5-mon-sep-13"><i class="fa fa-check"></i><b>11.3</b> Day 5: Mon Sep 13</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html"><i class="fa fa-check"></i><b>12</b> Linear Systems in R</a>
<ul>
<li class="chapter" data-level="12.1" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#getting-started-with-r"><i class="fa fa-check"></i><b>12.1</b> Getting started with R</a></li>
<li class="chapter" data-level="12.2" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#building-vectors-and-matrices"><i class="fa fa-check"></i><b>12.2</b> Building Vectors and Matrices</a></li>
<li class="chapter" data-level="12.3" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#solving-a-linear-system"><i class="fa fa-check"></i><b>12.3</b> Solving a Linear System</a></li>
<li class="chapter" data-level="12.4" data-path="linear-systems-in-r.html"><a href="linear-systems-in-r.html#solving-another-linear-system"><i class="fa fa-check"></i><b>12.4</b> Solving another Linear System</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="linear-dependence.html"><a href="linear-dependence.html"><i class="fa fa-check"></i><b>13</b> Linear Dependence</a>
<ul>
<li class="chapter" data-level="13.1" data-path="linear-dependence.html"><a href="linear-dependence.html#example-1-a-7x9-integer-matrix"><i class="fa fa-check"></i><b>13.1</b> Example 1: a 7x9 integer matrix</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="linear-dependence.html"><a href="linear-dependence.html#solution-to-the-nonhomogeneous-equations-ax-b"><i class="fa fa-check"></i><b>13.1.1</b> Solution to the nonhomogeneous equations Ax = b</a></li>
<li class="chapter" data-level="13.1.2" data-path="linear-dependence.html"><a href="linear-dependence.html#solution-to-the-nonhomogeneous-equations-ax-0"><i class="fa fa-check"></i><b>13.1.2</b> Solution to the nonhomogeneous equations Ax = 0</a></li>
<li class="chapter" data-level="13.1.3" data-path="linear-dependence.html"><a href="linear-dependence.html#linearly-dependent-columns"><i class="fa fa-check"></i><b>13.1.3</b> Linearly dependent columns</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="linear-dependence.html"><a href="linear-dependence.html#a-5-x-6-numerical-matrix"><i class="fa fa-check"></i><b>13.2</b> A 5 x 6 Numerical Matrix</a></li>
<li class="chapter" data-level="13.3" data-path="linear-dependence.html"><a href="linear-dependence.html#random-matrices"><i class="fa fa-check"></i><b>13.3</b> Random Matrices</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="matrix-multiplication.html"><a href="matrix-multiplication.html"><i class="fa fa-check"></i><b>14</b> Matrix Multiplication</a>
<ul>
<li class="chapter" data-level="14.1" data-path="matrix-multiplication.html"><a href="matrix-multiplication.html#multiplying-matrices"><i class="fa fa-check"></i><b>14.1</b> Multiplying matrices</a></li>
<li class="chapter" data-level="14.2" data-path="matrix-multiplication.html"><a href="matrix-multiplication.html#transpose"><i class="fa fa-check"></i><b>14.2</b> Transpose</a></li>
<li class="chapter" data-level="14.3" data-path="matrix-multiplication.html"><a href="matrix-multiplication.html#identity-matrix"><i class="fa fa-check"></i><b>14.3</b> Identity Matrix</a></li>
<li class="chapter" data-level="14.4" data-path="matrix-multiplication.html"><a href="matrix-multiplication.html#writing-loops"><i class="fa fa-check"></i><b>14.4</b> Writing Loops</a></li>
<li class="chapter" data-level="14.5" data-path="matrix-multiplication.html"><a href="matrix-multiplication.html#matrix-inverses"><i class="fa fa-check"></i><b>14.5</b> Matrix Inverses</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="eigenvectors.html"><a href="eigenvectors.html"><i class="fa fa-check"></i><b>15</b> Eigenvectors</a>
<ul>
<li class="chapter" data-level="15.1" data-path="eigenvectors.html"><a href="eigenvectors.html#computing-eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>15.1</b> Computing Eigenvectors and Eigenvalues</a></li>
<li class="chapter" data-level="15.2" data-path="eigenvectors.html"><a href="eigenvectors.html#diagonalization-1"><i class="fa fa-check"></i><b>15.2</b> Diagonalization</a></li>
<li class="chapter" data-level="15.3" data-path="eigenvectors.html"><a href="eigenvectors.html#dynamical-systems"><i class="fa fa-check"></i><b>15.3</b> Dynamical Systems</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="eigenvectors.html"><a href="eigenvectors.html#plotting-dynamical-systems"><i class="fa fa-check"></i><b>15.3.1</b> Plotting dynamical systems</a></li>
<li class="chapter" data-level="15.3.2" data-path="eigenvectors.html"><a href="eigenvectors.html#video-example"><i class="fa fa-check"></i><b>15.3.2</b> Video Example</a></li>
<li class="chapter" data-level="15.3.3" data-path="eigenvectors.html"><a href="eigenvectors.html#checkpoint-question-for-today"><i class="fa fa-check"></i><b>15.3.3</b> CheckPoint Question for today</a></li>
<li class="chapter" data-level="15.3.4" data-path="eigenvectors.html"><a href="eigenvectors.html#discussion-question-1"><i class="fa fa-check"></i><b>15.3.4</b> Discussion Question 1</a></li>
<li class="chapter" data-level="15.3.5" data-path="eigenvectors.html"><a href="eigenvectors.html#discussion-question-2"><i class="fa fa-check"></i><b>15.3.5</b> Discussion Question 2</a></li>
<li class="chapter" data-level="15.3.6" data-path="eigenvectors.html"><a href="eigenvectors.html#discussion-question-3"><i class="fa fa-check"></i><b>15.3.6</b> Discussion Question 3</a></li>
<li class="chapter" data-level="15.3.7" data-path="eigenvectors.html"><a href="eigenvectors.html#discussion-question-4"><i class="fa fa-check"></i><b>15.3.7</b> Discussion Question 4</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="eigenvectors.html"><a href="eigenvectors.html#northern-spotted-owl"><i class="fa fa-check"></i><b>15.4</b> Northern Spotted Owl</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="eigenvectors.html"><a href="eigenvectors.html#the-dynamical-system"><i class="fa fa-check"></i><b>15.4.1</b> The Dynamical System</a></li>
<li class="chapter" data-level="15.4.2" data-path="eigenvectors.html"><a href="eigenvectors.html#eigenanalysis"><i class="fa fa-check"></i><b>15.4.2</b> Eigenanalysis</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="eigenvectors.html"><a href="eigenvectors.html#fibonacci-numbers"><i class="fa fa-check"></i><b>15.5</b> Fibonacci Numbers</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html"><i class="fa fa-check"></i><b>16</b> Complex Eigenvalues</a>
<ul>
<li class="chapter" data-level="16.1" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#motivating-example"><i class="fa fa-check"></i><b>16.1</b> Motivating Example</a></li>
<li class="chapter" data-level="16.2" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#rotation-dilation-matrices"><i class="fa fa-check"></i><b>16.2</b> Rotation-Dilation Matrices</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#example-1"><i class="fa fa-check"></i><b>16.2.1</b> Example 1</a></li>
<li class="chapter" data-level="16.2.2" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#example-2"><i class="fa fa-check"></i><b>16.2.2</b> Example 2</a></li>
<li class="chapter" data-level="16.2.3" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#example-3"><i class="fa fa-check"></i><b>16.2.3</b> Example 3</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#general-2x2-matrices-with-complex-eigenvalues"><i class="fa fa-check"></i><b>16.3</b> General 2x2 Matrices with Complex Eigenvalues</a></li>
<li class="chapter" data-level="16.4" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#examples-from-class"><i class="fa fa-check"></i><b>16.4</b> Examples from class</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#section"><i class="fa fa-check"></i><b>16.4.1</b> </a></li>
<li class="chapter" data-level="16.4.2" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#section-1"><i class="fa fa-check"></i><b>16.4.2</b> </a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="complex-eigenvalues.html"><a href="complex-eigenvalues.html#the-checkpoint-question"><i class="fa fa-check"></i><b>16.5</b> The checkpoint question</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="network-centralities.html"><a href="network-centralities.html"><i class="fa fa-check"></i><b>17</b> Network Centralities</a>
<ul>
<li class="chapter" data-level="17.1" data-path="network-centralities.html"><a href="network-centralities.html#graphs-and-networks"><i class="fa fa-check"></i><b>17.1</b> Graphs and Networks</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="network-centralities.html"><a href="network-centralities.html#adjacency-matrices"><i class="fa fa-check"></i><b>17.1.1</b> Adjacency Matrices</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="network-centralities.html"><a href="network-centralities.html#degree-centrality"><i class="fa fa-check"></i><b>17.2</b> Degree Centrality</a></li>
<li class="chapter" data-level="17.3" data-path="network-centralities.html"><a href="network-centralities.html#goulds-index"><i class="fa fa-check"></i><b>17.3</b> Gould’s Index</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="network-centralities.html"><a href="network-centralities.html#step-1-add-layovers"><i class="fa fa-check"></i><b>17.3.1</b> Step 1: Add Layovers</a></li>
<li class="chapter" data-level="17.3.2" data-path="network-centralities.html"><a href="network-centralities.html#step-2-dynamical-system"><i class="fa fa-check"></i><b>17.3.2</b> Step 2: Dynamical System</a></li>
<li class="chapter" data-level="17.3.3" data-path="network-centralities.html"><a href="network-centralities.html#step-4-eigen-analysis"><i class="fa fa-check"></i><b>17.3.3</b> Step 4: Eigen-analysis</a></li>
<li class="chapter" data-level="17.3.4" data-path="network-centralities.html"><a href="network-centralities.html#step-5-visualize"><i class="fa fa-check"></i><b>17.3.4</b> Step 5: Visualize</a></li>
<li class="chapter" data-level="17.3.5" data-path="network-centralities.html"><a href="network-centralities.html#gould-index-summary"><i class="fa fa-check"></i><b>17.3.5</b> Gould Index Summary</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Quiz Review</b></span></li>
<li class="chapter" data-level="18" data-path="exam-1-review.html"><a href="exam-1-review.html"><i class="fa fa-check"></i><b>18</b> Exam 1 Review</a>
<ul>
<li class="chapter" data-level="18.1" data-path="exam-1-review.html"><a href="exam-1-review.html#overview"><i class="fa fa-check"></i><b>18.1</b> Overview</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="exam-1-review.html"><a href="exam-1-review.html#vocabulary-and-concepts"><i class="fa fa-check"></i><b>18.1.1</b> Vocabulary and Concepts</a></li>
<li class="chapter" data-level="18.1.2" data-path="exam-1-review.html"><a href="exam-1-review.html#skills"><i class="fa fa-check"></i><b>18.1.2</b> Skills</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="exam-1-review.html"><a href="exam-1-review.html#practice-problems"><i class="fa fa-check"></i><b>18.2</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="exam-1-review.html"><a href="exam-1-review.html#section-2"><i class="fa fa-check"></i><b>18.2.1</b> </a></li>
<li class="chapter" data-level="18.2.2" data-path="exam-1-review.html"><a href="exam-1-review.html#section-3"><i class="fa fa-check"></i><b>18.2.2</b> </a></li>
<li class="chapter" data-level="18.2.3" data-path="exam-1-review.html"><a href="exam-1-review.html#section-4"><i class="fa fa-check"></i><b>18.2.3</b> </a></li>
<li class="chapter" data-level="18.2.4" data-path="exam-1-review.html"><a href="exam-1-review.html#section-5"><i class="fa fa-check"></i><b>18.2.4</b> </a></li>
<li class="chapter" data-level="18.2.5" data-path="exam-1-review.html"><a href="exam-1-review.html#section-6"><i class="fa fa-check"></i><b>18.2.5</b> </a></li>
<li class="chapter" data-level="18.2.6" data-path="exam-1-review.html"><a href="exam-1-review.html#section-7"><i class="fa fa-check"></i><b>18.2.6</b> </a></li>
<li class="chapter" data-level="18.2.7" data-path="exam-1-review.html"><a href="exam-1-review.html#section-8"><i class="fa fa-check"></i><b>18.2.7</b> </a></li>
<li class="chapter" data-level="18.2.8" data-path="exam-1-review.html"><a href="exam-1-review.html#section-9"><i class="fa fa-check"></i><b>18.2.8</b> </a></li>
<li class="chapter" data-level="18.2.9" data-path="exam-1-review.html"><a href="exam-1-review.html#section-10"><i class="fa fa-check"></i><b>18.2.9</b> </a></li>
<li class="chapter" data-level="18.2.10" data-path="exam-1-review.html"><a href="exam-1-review.html#section-11"><i class="fa fa-check"></i><b>18.2.10</b> </a></li>
<li class="chapter" data-level="18.2.11" data-path="exam-1-review.html"><a href="exam-1-review.html#section-12"><i class="fa fa-check"></i><b>18.2.11</b> </a></li>
<li class="chapter" data-level="18.2.12" data-path="exam-1-review.html"><a href="exam-1-review.html#section-13"><i class="fa fa-check"></i><b>18.2.12</b> </a></li>
<li class="chapter" data-level="18.2.13" data-path="exam-1-review.html"><a href="exam-1-review.html#section-14"><i class="fa fa-check"></i><b>18.2.13</b> </a></li>
<li class="chapter" data-level="18.2.14" data-path="exam-1-review.html"><a href="exam-1-review.html#section-15"><i class="fa fa-check"></i><b>18.2.14</b> </a></li>
<li class="chapter" data-level="18.2.15" data-path="exam-1-review.html"><a href="exam-1-review.html#section-16"><i class="fa fa-check"></i><b>18.2.15</b> </a></li>
<li class="chapter" data-level="18.2.16" data-path="exam-1-review.html"><a href="exam-1-review.html#challenge"><i class="fa fa-check"></i><b>18.2.16</b> Challenge</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="exam-1-review.html"><a href="exam-1-review.html#solutions-to-practice-problems"><i class="fa fa-check"></i><b>18.3</b> Solutions to Practice Problems</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="exam-1-review.html"><a href="exam-1-review.html#section-17"><i class="fa fa-check"></i><b>18.3.1</b> </a></li>
<li class="chapter" data-level="18.3.2" data-path="exam-1-review.html"><a href="exam-1-review.html#section-18"><i class="fa fa-check"></i><b>18.3.2</b> </a></li>
<li class="chapter" data-level="18.3.3" data-path="exam-1-review.html"><a href="exam-1-review.html#section-19"><i class="fa fa-check"></i><b>18.3.3</b> </a></li>
<li class="chapter" data-level="18.3.4" data-path="exam-1-review.html"><a href="exam-1-review.html#section-20"><i class="fa fa-check"></i><b>18.3.4</b> </a></li>
<li class="chapter" data-level="18.3.5" data-path="exam-1-review.html"><a href="exam-1-review.html#section-21"><i class="fa fa-check"></i><b>18.3.5</b> </a></li>
<li class="chapter" data-level="18.3.6" data-path="exam-1-review.html"><a href="exam-1-review.html#section-22"><i class="fa fa-check"></i><b>18.3.6</b> </a></li>
<li class="chapter" data-level="18.3.7" data-path="exam-1-review.html"><a href="exam-1-review.html#section-23"><i class="fa fa-check"></i><b>18.3.7</b> </a></li>
<li class="chapter" data-level="18.3.8" data-path="exam-1-review.html"><a href="exam-1-review.html#section-24"><i class="fa fa-check"></i><b>18.3.8</b> </a></li>
<li class="chapter" data-level="18.3.9" data-path="exam-1-review.html"><a href="exam-1-review.html#section-25"><i class="fa fa-check"></i><b>18.3.9</b> </a></li>
<li class="chapter" data-level="18.3.10" data-path="exam-1-review.html"><a href="exam-1-review.html#section-26"><i class="fa fa-check"></i><b>18.3.10</b> </a></li>
<li class="chapter" data-level="18.3.11" data-path="exam-1-review.html"><a href="exam-1-review.html#section-27"><i class="fa fa-check"></i><b>18.3.11</b> </a></li>
<li class="chapter" data-level="18.3.12" data-path="exam-1-review.html"><a href="exam-1-review.html#section-28"><i class="fa fa-check"></i><b>18.3.12</b> </a></li>
<li class="chapter" data-level="18.3.13" data-path="exam-1-review.html"><a href="exam-1-review.html#section-29"><i class="fa fa-check"></i><b>18.3.13</b> </a></li>
<li class="chapter" data-level="18.3.14" data-path="exam-1-review.html"><a href="exam-1-review.html#section-30"><i class="fa fa-check"></i><b>18.3.14</b> </a></li>
<li class="chapter" data-level="18.3.15" data-path="exam-1-review.html"><a href="exam-1-review.html#section-31"><i class="fa fa-check"></i><b>18.3.15</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="exam-2-review.html"><a href="exam-2-review.html"><i class="fa fa-check"></i><b>19</b> Exam 2 Review</a>
<ul>
<li class="chapter" data-level="19.1" data-path="exam-2-review.html"><a href="exam-2-review.html#overview-1"><i class="fa fa-check"></i><b>19.1</b> Overview</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="exam-2-review.html"><a href="exam-2-review.html#vocabulary-and-concepts-1"><i class="fa fa-check"></i><b>19.1.1</b> Vocabulary and Concepts</a></li>
<li class="chapter" data-level="19.1.2" data-path="exam-2-review.html"><a href="exam-2-review.html#vocabulary-and-concepts-2"><i class="fa fa-check"></i><b>19.1.2</b> Vocabulary and Concepts</a></li>
<li class="chapter" data-level="19.1.3" data-path="exam-2-review.html"><a href="exam-2-review.html#skills-1"><i class="fa fa-check"></i><b>19.1.3</b> Skills</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="exam-2-review.html"><a href="exam-2-review.html#practice-problems-1"><i class="fa fa-check"></i><b>19.2</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="exam-2-review.html"><a href="exam-2-review.html#section-32"><i class="fa fa-check"></i><b>19.2.1</b> </a></li>
<li class="chapter" data-level="19.2.2" data-path="exam-2-review.html"><a href="exam-2-review.html#section-33"><i class="fa fa-check"></i><b>19.2.2</b> </a></li>
<li class="chapter" data-level="19.2.3" data-path="exam-2-review.html"><a href="exam-2-review.html#section-34"><i class="fa fa-check"></i><b>19.2.3</b> </a></li>
<li class="chapter" data-level="19.2.4" data-path="exam-2-review.html"><a href="exam-2-review.html#section-35"><i class="fa fa-check"></i><b>19.2.4</b> </a></li>
<li class="chapter" data-level="19.2.5" data-path="exam-2-review.html"><a href="exam-2-review.html#section-36"><i class="fa fa-check"></i><b>19.2.5</b> </a></li>
<li class="chapter" data-level="19.2.6" data-path="exam-2-review.html"><a href="exam-2-review.html#section-37"><i class="fa fa-check"></i><b>19.2.6</b> </a></li>
<li class="chapter" data-level="19.2.7" data-path="exam-2-review.html"><a href="exam-2-review.html#section-38"><i class="fa fa-check"></i><b>19.2.7</b> </a></li>
<li class="chapter" data-level="19.2.8" data-path="exam-2-review.html"><a href="exam-2-review.html#section-39"><i class="fa fa-check"></i><b>19.2.8</b> </a></li>
<li class="chapter" data-level="19.2.9" data-path="exam-2-review.html"><a href="exam-2-review.html#section-40"><i class="fa fa-check"></i><b>19.2.9</b> </a></li>
<li class="chapter" data-level="19.2.10" data-path="exam-2-review.html"><a href="exam-2-review.html#section-41"><i class="fa fa-check"></i><b>19.2.10</b> </a></li>
<li class="chapter" data-level="19.2.11" data-path="exam-2-review.html"><a href="exam-2-review.html#section-42"><i class="fa fa-check"></i><b>19.2.11</b> </a></li>
<li class="chapter" data-level="19.2.12" data-path="exam-2-review.html"><a href="exam-2-review.html#section-43"><i class="fa fa-check"></i><b>19.2.12</b> </a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="exam-2-review.html"><a href="exam-2-review.html#solutions-to-practice-problems-1"><i class="fa fa-check"></i><b>19.3</b> Solutions to Practice Problems</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="exam-2-review.html"><a href="exam-2-review.html#section-44"><i class="fa fa-check"></i><b>19.3.1</b> </a></li>
<li class="chapter" data-level="19.3.2" data-path="exam-2-review.html"><a href="exam-2-review.html#section-45"><i class="fa fa-check"></i><b>19.3.2</b> </a></li>
<li class="chapter" data-level="19.3.3" data-path="exam-2-review.html"><a href="exam-2-review.html#section-46"><i class="fa fa-check"></i><b>19.3.3</b> </a></li>
<li class="chapter" data-level="19.3.4" data-path="exam-2-review.html"><a href="exam-2-review.html#section-47"><i class="fa fa-check"></i><b>19.3.4</b> </a></li>
<li class="chapter" data-level="19.3.5" data-path="exam-2-review.html"><a href="exam-2-review.html#section-48"><i class="fa fa-check"></i><b>19.3.5</b> </a></li>
<li class="chapter" data-level="19.3.6" data-path="exam-2-review.html"><a href="exam-2-review.html#section-49"><i class="fa fa-check"></i><b>19.3.6</b> </a></li>
<li class="chapter" data-level="19.3.7" data-path="exam-2-review.html"><a href="exam-2-review.html#section-50"><i class="fa fa-check"></i><b>19.3.7</b> </a></li>
<li class="chapter" data-level="19.3.8" data-path="exam-2-review.html"><a href="exam-2-review.html#section-51"><i class="fa fa-check"></i><b>19.3.8</b> </a></li>
<li class="chapter" data-level="19.3.9" data-path="exam-2-review.html"><a href="exam-2-review.html#section-52"><i class="fa fa-check"></i><b>19.3.9</b> </a></li>
<li class="chapter" data-level="19.3.10" data-path="exam-2-review.html"><a href="exam-2-review.html#section-53"><i class="fa fa-check"></i><b>19.3.10</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="exam-3-review.html"><a href="exam-3-review.html"><i class="fa fa-check"></i><b>20</b> Exam 3 Review</a>
<ul>
<li class="chapter" data-level="20.1" data-path="exam-3-review.html"><a href="exam-3-review.html#overview-2"><i class="fa fa-check"></i><b>20.1</b> Overview</a></li>
<li class="chapter" data-level="20.2" data-path="exam-3-review.html"><a href="exam-3-review.html#vocabulary-concepts-and-skills"><i class="fa fa-check"></i><b>20.2</b> Vocabulary, Concepts and Skills</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="exam-3-review.html"><a href="exam-3-review.html#skills-2"><i class="fa fa-check"></i><b>20.2.1</b> Skills</a></li>
<li class="chapter" data-level="20.2.2" data-path="exam-3-review.html"><a href="exam-3-review.html#vocabulary"><i class="fa fa-check"></i><b>20.2.2</b> Vocabulary</a></li>
<li class="chapter" data-level="20.2.3" data-path="exam-3-review.html"><a href="exam-3-review.html#conceptual-thinking"><i class="fa fa-check"></i><b>20.2.3</b> Conceptual Thinking</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="exam-3-review.html"><a href="exam-3-review.html#practice-problems-2"><i class="fa fa-check"></i><b>20.3</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="exam-3-review.html"><a href="exam-3-review.html#section-54"><i class="fa fa-check"></i><b>20.3.1</b> </a></li>
<li class="chapter" data-level="20.3.2" data-path="exam-3-review.html"><a href="exam-3-review.html#section-55"><i class="fa fa-check"></i><b>20.3.2</b> </a></li>
<li class="chapter" data-level="20.3.3" data-path="exam-3-review.html"><a href="exam-3-review.html#section-56"><i class="fa fa-check"></i><b>20.3.3</b> </a></li>
<li class="chapter" data-level="20.3.4" data-path="exam-3-review.html"><a href="exam-3-review.html#section-57"><i class="fa fa-check"></i><b>20.3.4</b> </a></li>
<li class="chapter" data-level="20.3.5" data-path="exam-3-review.html"><a href="exam-3-review.html#section-58"><i class="fa fa-check"></i><b>20.3.5</b> </a></li>
<li class="chapter" data-level="20.3.6" data-path="exam-3-review.html"><a href="exam-3-review.html#section-59"><i class="fa fa-check"></i><b>20.3.6</b> </a></li>
<li class="chapter" data-level="20.3.7" data-path="exam-3-review.html"><a href="exam-3-review.html#section-60"><i class="fa fa-check"></i><b>20.3.7</b> </a></li>
<li class="chapter" data-level="20.3.8" data-path="exam-3-review.html"><a href="exam-3-review.html#section-61"><i class="fa fa-check"></i><b>20.3.8</b> </a></li>
<li class="chapter" data-level="20.3.9" data-path="exam-3-review.html"><a href="exam-3-review.html#section-62"><i class="fa fa-check"></i><b>20.3.9</b> </a></li>
<li class="chapter" data-level="20.3.10" data-path="exam-3-review.html"><a href="exam-3-review.html#section-63"><i class="fa fa-check"></i><b>20.3.10</b> </a></li>
<li class="chapter" data-level="20.3.11" data-path="exam-3-review.html"><a href="exam-3-review.html#section-64"><i class="fa fa-check"></i><b>20.3.11</b> </a></li>
<li class="chapter" data-level="20.3.12" data-path="exam-3-review.html"><a href="exam-3-review.html#section-65"><i class="fa fa-check"></i><b>20.3.12</b> </a></li>
<li class="chapter" data-level="20.3.13" data-path="exam-3-review.html"><a href="exam-3-review.html#section-66"><i class="fa fa-check"></i><b>20.3.13</b> </a></li>
<li class="chapter" data-level="20.3.14" data-path="exam-3-review.html"><a href="exam-3-review.html#section-67"><i class="fa fa-check"></i><b>20.3.14</b> </a></li>
<li class="chapter" data-level="20.3.15" data-path="exam-3-review.html"><a href="exam-3-review.html#section-68"><i class="fa fa-check"></i><b>20.3.15</b> </a></li>
<li class="chapter" data-level="20.3.16" data-path="exam-3-review.html"><a href="exam-3-review.html#section-69"><i class="fa fa-check"></i><b>20.3.16</b> </a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="exam-3-review.html"><a href="exam-3-review.html#solutions-to-practice-problems-2"><i class="fa fa-check"></i><b>20.4</b> Solutions to Practice Problems</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="exam-3-review.html"><a href="exam-3-review.html#section-70"><i class="fa fa-check"></i><b>20.4.1</b> </a></li>
<li class="chapter" data-level="20.4.2" data-path="exam-3-review.html"><a href="exam-3-review.html#section-71"><i class="fa fa-check"></i><b>20.4.2</b> </a></li>
<li class="chapter" data-level="20.4.3" data-path="exam-3-review.html"><a href="exam-3-review.html#section-72"><i class="fa fa-check"></i><b>20.4.3</b> </a></li>
<li class="chapter" data-level="20.4.4" data-path="exam-3-review.html"><a href="exam-3-review.html#section-73"><i class="fa fa-check"></i><b>20.4.4</b> </a></li>
<li class="chapter" data-level="20.4.5" data-path="exam-3-review.html"><a href="exam-3-review.html#section-74"><i class="fa fa-check"></i><b>20.4.5</b> </a></li>
<li class="chapter" data-level="20.4.6" data-path="exam-3-review.html"><a href="exam-3-review.html#section-75"><i class="fa fa-check"></i><b>20.4.6</b> </a></li>
<li class="chapter" data-level="20.4.7" data-path="exam-3-review.html"><a href="exam-3-review.html#section-76"><i class="fa fa-check"></i><b>20.4.7</b> </a></li>
<li class="chapter" data-level="20.4.8" data-path="exam-3-review.html"><a href="exam-3-review.html#section-77"><i class="fa fa-check"></i><b>20.4.8</b> </a></li>
<li class="chapter" data-level="20.4.9" data-path="exam-3-review.html"><a href="exam-3-review.html#section-78"><i class="fa fa-check"></i><b>20.4.9</b> </a></li>
<li class="chapter" data-level="20.4.10" data-path="exam-3-review.html"><a href="exam-3-review.html#section-79"><i class="fa fa-check"></i><b>20.4.10</b> </a></li>
<li class="chapter" data-level="20.4.11" data-path="exam-3-review.html"><a href="exam-3-review.html#section-80"><i class="fa fa-check"></i><b>20.4.11</b> </a></li>
<li class="chapter" data-level="20.4.12" data-path="exam-3-review.html"><a href="exam-3-review.html#section-81"><i class="fa fa-check"></i><b>20.4.12</b> </a></li>
<li class="chapter" data-level="20.4.13" data-path="exam-3-review.html"><a href="exam-3-review.html#section-82"><i class="fa fa-check"></i><b>20.4.13</b> </a></li>
<li class="chapter" data-level="20.4.14" data-path="exam-3-review.html"><a href="exam-3-review.html#section-83"><i class="fa fa-check"></i><b>20.4.14</b> </a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MATH 236: Linear Algebra</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exam-3-review" class="section level1" number="20">
<h1><span class="header-section-number">Section 20</span> Exam 3 Review</h1>
<div id="overview-2" class="section level2" number="20.1">
<h2><span class="header-section-number">20.1</span> Overview</h2>
<p>Our third exam covers <em>eigenvectors</em> and <em>eigenvalues</em> and a little bit of <em>orthogonality</em>. This covers sections 5.1-5.6 and 6.1-6.2.</p>
<p>The exam will be in the same style as the first two exams:</p>
<ul>
<li>I will hand it out right away, even a few minutes early, so you can start right on time.</li>
<li>You must turn it in by 9:35 (for the 8:30 class) and 10:45 for the 10:50 class). No exceptions. The next class needs to come in and get started.</li>
<li>No calculators are allowed, and none are needed.</li>
<li>If row reductions are needed, they will be easy (integer) calculations, and there will not be many.</li>
<li>It will be closed book but you can bring a 3" x 5" <strong>note card</strong> with notes written on both sides. These notes should be hand written by you. You do not need to turn in the note card with the exam.</li>
<li>There will be some basic calculations, but the problems will focus more on the ideas than on the calculations.</li>
<li>I will ask some problems that are very similar to homework problems, Edfinity problems, and examples from class or the videos.</li>
<li>I will ask other problems that are somewhat different from things you have done. On these, you are to apply your knowledge in a slightly new setting to demonstrate an even higher mastery of the material.</li>
<li>You will be allowed to re-write one problem to earn back half of the points that you lost. This will be due the class period after I hand the exam back.</li>
<li>The exam is worth 12% of your course grade as outlined in the <a href="https://docs.google.com/document/d/1uE95uWoV994QJ6YyrR7yBMV7MATzYO6XI4xd_q4-sqc">syllabus</a>.</li>
</ul>
<p>The best way to study is to do practice problems. The Exam will have calculation problems (like Edfinity) and more conceptual problems (like the problem sets). Here are some ways to practice:</p>
<ul>
<li>Make sure that you have mastered the Vocabulary, Skills and Concepts listed below.</li>
<li>Look over the Edfinity homework assingments</li>
<li>Look over and redo the class examples problems.</li>
<li>Look at class examples that we didn’t get to.</li>
<li>Try to resolve the Problem Sets and compare your answers to the solutions.</li>
<li>Do the practice problems below. Compare your answers to the solutions.</li>
</ul>
</div>
<div id="vocabulary-concepts-and-skills" class="section level2" number="20.2">
<h2><span class="header-section-number">20.2</span> Vocabulary, Concepts and Skills</h2>
<p>Here are the knowledge and skills you should master by the end of the fifth and sixth weeks.</p>
<div id="skills-2" class="section level3" number="20.2.1">
<h3><span class="header-section-number">20.2.1</span> Skills</h3>
<ul>
<li><p>Check whether a given vector <span class="math inline">\(\mathsf{v}\)</span> is an eigenvector for square matrix <span class="math inline">\(A\)</span>.</p></li>
<li><p>Find the eigenvalues of a matrix <span class="math inline">\(2 \times 2\)</span> matrix by hand, using the characteristic equation</p></li>
<li><p>Find the eigenvalues of a triangular matrix by inspection.</p></li>
<li><p>Given the eigenvalues of matrix <span class="math inline">\(A\)</span>, find the eigenvectors by solving <span class="math inline">\((A - \lambda I) = \mathbf{0}\)</span>.</p></li>
<li><p>Find the eigenvalues and eigenvectors of an <span class="math inline">\(n \times n\)</span> matrix <span class="math inline">\(A\)</span> by reading RStudio output.</p></li>
<li><p>Determine whether a matrix is diagonalizable.</p></li>
<li><p>Factor a diagonalizable <span class="math inline">\(n \times n\)</span> matrix as <span class="math inline">\(A = PDP^{-1}\)</span> where <span class="math inline">\(D\)</span> is a diagonal matrix of eigenvalues and <span class="math inline">\(P\)</span> is the matrix whose columns are the corresponding eigenvectors. You only have to compute <span class="math inline">\(P^{-1}\)</span> in the 2x2 case.</p></li>
<li><p>Compute matrix powers using the diagonalization.</p></li>
<li><p>Given the eigenvalues and eigenvectors, factor a <span class="math inline">\(2 \times 2\)</span> matrix with complex eigenvalues as <span class="math inline">\(A = P R P^{-1}\)</span> where <span class="math inline">\(R\)</span> is a rotation-dilation matrix <span class="math inline">\(\begin{bmatrix} a &amp; -b \\ b &amp; a \end{bmatrix}\)</span> and <span class="math inline">\(P = [ \mathsf{w}, \mathsf{u}]\)</span> where <span class="math inline">\(\mathsf{v} = \mathsf{u} + i \mathsf{w}\)</span> is the eigenvector for <span class="math inline">\(\lambda = a + b i\)</span>.</p></li>
<li><p>Find the angle of rotation and the scaling factor in a <span class="math inline">\(2 \times 2\)</span> matrix with complex eigenvalues.</p></li>
<li><p>Use the dominant eigenvalue and dominant eigenvector to determine the long-term behavior of a dynamical system.</p></li>
<li><p>Use eigenvalues to investigate a population modeled with a Leslie matrix.</p></li>
<li><p>Give a close-formula for a dynamical system using the eigen decomposition of a matrix</p></li>
<li><p>More coming from the orthogonality sections.</p></li>
</ul>
</div>
<div id="vocabulary" class="section level3" number="20.2.2">
<h3><span class="header-section-number">20.2.2</span> Vocabulary</h3>
<p>I should know and be able to use and explain the following <strong>terms</strong> or <strong>properties</strong>.</p>
<ul>
<li>eigenvalue, eigenvector and eigenspace</li>
<li>characteristic equation</li>
<li>diagonalizable matrix</li>
<li>similar matrices</li>
<li>algebraic multiplicity of an eigenvalue</li>
<li>geometric multiplicity of an eigenvalue</li>
<li>rotation-dilation matrix</li>
<li>discrete dynamical system</li>
<li>trajectory</li>
<li>dominant eigenvalue and dominant eigenvector</li>
<li>population model</li>
<li>Leslie matrix</li>
</ul>
</div>
<div id="conceptual-thinking" class="section level3" number="20.2.3">
<h3><span class="header-section-number">20.2.3</span> Conceptual Thinking</h3>
<p>I should understand and be able to explain the following <strong>concepts</strong>:</p>
<ul>
<li><p>An eigenspace of <span class="math inline">\(A\)</span> is a subspace that is fixed under the linear transformation <span class="math inline">\(T(\mathsf{x}) = A \mathsf{x}\)</span>.</p></li>
<li><p>An eigenvalue <span class="math inline">\(\lambda\)</span> with <span class="math inline">\(1 &lt;| \lambda |\)</span> corresponds to expansion.</p></li>
<li><p>An eigenvalue <span class="math inline">\(\lambda\)</span> with <span class="math inline">\(0 &lt; | \lambda | &lt; 1\)</span> corresponds to contraction.</p></li>
<li><p>A complex eigenvalue corresponds to a rotation in a 2D subspace.</p></li>
<li><p>The eigenspace for <span class="math inline">\(\lambda\)</span> is the subspace <span class="math inline">\(E_\lambda = \mathrm{Nul}(A - \lambda I)\)</span>.</p></li>
<li><p>A matrix is not diagonalizable when it has an eigenvalue whose algebraic multiplicity is larger than its geometric multiplicity.</p></li>
<li><p>The long-term behavior of a dynamical system is determined by its dominant eigenvalue and eigenvector.</p></li>
<li><p>Population model predicts one of: long term growth, extinction, convergence to a stable population.</p></li>
</ul>
</div>
</div>
<div id="practice-problems-2" class="section level2" number="20.3">
<h2><span class="header-section-number">20.3</span> Practice Problems</h2>
<div id="section-54" class="section level3" number="20.3.1">
<h3><span class="header-section-number">20.3.1</span> </h3>
<p>Consider the <span class="math inline">\(3 \times 3\)</span> matrix
<span class="math display">\[
A = 
\left[
\begin{array}{rrr}
2 &amp; -1 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
-2 &amp; 5 &amp; -2 \\
\end{array}
\right]
\]</span>
with characteristic equation
<span class="math display">\[
p(\lambda) = -(\lambda -1)(\lambda -2)(\lambda +2).
\]</span>
Find the eigenvalues and corresponding eigenvectors for <span class="math inline">\(A\)</span>.</p>
</div>
<div id="section-55" class="section level3" number="20.3.2">
<h3><span class="header-section-number">20.3.2</span> </h3>
<p>Let <span class="math inline">\(A\)</span> be a <span class="math inline">\(2 \times 2\)</span> matrix. We view <span class="math inline">\(A\)</span> as a linear transformation from <span class="math inline">\(\mathbb{R}^2\)</span> to <span class="math inline">\(\mathbb{R}^2\)</span>. Describe the eigenvalues for each of the following types of matrices.</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A\)</span> maps all of <span class="math inline">\(\mathbb{R}^2\)</span> onto a line through the origin in <span class="math inline">\(\mathbb{R}^2\)</span>.</li>
<li><span class="math inline">\(A\)</span> is a reflection of <span class="math inline">\(\mathbb{R}^2\)</span> about a line through the origin</li>
<li><span class="math inline">\(A\)</span> is a reflection of <span class="math inline">\(\mathbb{R}^2\)</span> through the origin</li>
<li><span class="math inline">\(A\)</span> is a horizontal shear of the form d form
<span class="math display">\[
\begin{bmatrix} 1 &amp; a \\ 0 &amp; 1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
= \begin{bmatrix} x + a y \\ y \end{bmatrix}
\]</span></li>
<li><span class="math inline">\(A\)</span> is the projection onto the line <span class="math inline">\(y = 5x\)</span>.</li>
</ol>
</div>
<div id="section-56" class="section level3" number="20.3.3">
<h3><span class="header-section-number">20.3.3</span> </h3>
<p>Below are the eigenvalues of four different <span class="math inline">\(5 \times 5\)</span> matrices. For each, decide if the matrix is invertible and if it is diagonalizable.
Answer Yes, No or “Not enough information to determine this.”</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A\)</span> has eigenvalues <span class="math inline">\(\lambda = -4, -3,0,1, 2\)</span></li>
<li><span class="math inline">\(B\)</span> has eigenvalues <span class="math inline">\(\lambda = -3, -1, 1, \sqrt{2}, 8.\)</span></li>
<li><span class="math inline">\(C\)</span> has eigenvalues <span class="math inline">\(\lambda = 1, 2, 2, 7, 8.\)</span></li>
<li><span class="math inline">\(D\)</span> has eigenvalues <span class="math inline">\(\lambda = -1, 0, 3,3, 10\)</span></li>
</ol>
</div>
<div id="section-57" class="section level3" number="20.3.4">
<h3><span class="header-section-number">20.3.4</span> </h3>
<p>Here the diagonalization of a matrix:
<span class="math display">\[
 \mathsf{A}=\left[
\begin{array}{ccc}
 5 &amp; 2 &amp; -1 \\
 2 &amp; 1 &amp; 0 \\
 -1 &amp; 0 &amp; 1 \\
\end{array}
\right] = 
\left[
\begin{array}{ccc}
 -5 &amp; 0 &amp; 1 \\
 -2 &amp; 1 &amp; -2 \\
 1 &amp; 2 &amp; 1 \\
\end{array}
\right] \left[
\begin{array}{ccc}
 6 &amp; 0 &amp; 0 \\
 0 &amp; 1 &amp; 0 \\
 0 &amp; 0 &amp; 0 \\
\end{array}
\right]\left[
\begin{array}{ccc}
 -\frac{1}{6} &amp; -\frac{1}{15} &amp; \frac{1}{30} \\
 0 &amp; \frac{1}{5} &amp; \frac{2}{5} \\
 \frac{1}{6} &amp; -\frac{1}{3} &amp; \frac{1}{6} \\
\end{array}
\right].
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Is the matrix <span class="math inline">\(\mathsf{A}\)</span> invertible?</li>
<li>Find a nonzero vector in <span class="math inline">\(\mathrm{Nul}(\mathsf{A})\)</span> if one exists.</li>
<li>Find a steady-state vector <span class="math inline">\(\mathsf{v}\)</span> such that <span class="math inline">\(\mathsf{A} \mathsf{v} = \mathsf{v}\)</span> if one exists.</li>
<li>Give the coordinates of <span class="math inline">\(\mathsf{v} = [1,2,3]^T\)</span> in the eigenbasis without row reductions.</li>
<li>Find a formula for <span class="math inline">\(\mathsf{A}^{2021} \mathsf{v}\)</span> if <span class="math inline">\(\mathsf{v} = [1,2,3]^T\)</span> in terms of the eigenbasis.</li>
</ol>
</div>
<div id="section-58" class="section level3" number="20.3.5">
<h3><span class="header-section-number">20.3.5</span> </h3>
<p>The eigensystem of matrix <span class="math inline">\(A\)</span> is given below. It has complex eigenvalues.
<span class="math display">\[
\begin{bmatrix} 3 &amp; -5 \\ 1 &amp; -1 \end{bmatrix}, \qquad
\lambda = 1 \pm i,
\qquad
v = \begin{bmatrix} 2 \\ 1 \end{bmatrix} \pm \begin{bmatrix} 1 \\ 0 \end{bmatrix} i.
\]</span>
a. What angle does it rotate by?
b. What factor does it scale by?
c. Factor it as <span class="math inline">\(A = P R P^{-1}\)</span> where <span class="math inline">\(R\)</span> is a rotation-dilation matrix.</p>
</div>
<div id="section-59" class="section level3" number="20.3.6">
<h3><span class="header-section-number">20.3.6</span> </h3>
<p>Using the matrix <span class="math inline">\(B = \begin{bmatrix} .97 &amp; -.71 \\ .71 &amp; .97 \end{bmatrix}\)</span> and the starting vector <span class="math inline">\(\mathsf{v} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}\)</span>, I plotted the points
<span class="math display">\[\mathsf{v}, B \mathsf{v}, B^2\mathsf{v}, B^3 \mathsf{v}, \ldots.\]</span>
I saw that these points are, roughly, going around in a circle.</p>
<ol style="list-style-type: lower-alpha">
<li><p>How many multiplications by <span class="math inline">\(B\)</span> does it take to get back around to the positive <span class="math inline">\(x\)</span>-axis?</p></li>
<li><p>When I come full circle, am I closer to the origin, farther from the origin, or the same distance to the origin?</p></li>
</ol>
</div>
<div id="section-60" class="section level3" number="20.3.7">
<h3><span class="header-section-number">20.3.7</span> </h3>
<p>For each matrix below, decide if it is diagonalizable. You do not need to diagonalize the matrix (though you can!), but you must give a reason for why the matrix is or is not diagonalizable.</p>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(A = \begin{bmatrix} 0 &amp; -4 &amp; 2 \\ 2 &amp; -4 &amp; -1 \\ -6 &amp; 4 &amp; 7 \end{bmatrix}\)</span> has eigenvalues <span class="math inline">\(4, -1, 0\)</span>.</p></li>
<li><p><span class="math inline">\(B = \begin{bmatrix} 3 &amp; -1 &amp; 2 \\ -1 &amp; 3 &amp; 2 \\ 2&amp;2 &amp; 0 \end{bmatrix}\)</span> has eigenvalues <span class="math inline">\(4,4,-2\)</span>.</p></li>
</ol>
</div>
<div id="section-61" class="section level3" number="20.3.8">
<h3><span class="header-section-number">20.3.8</span> </h3>
<p>Consider the matrix with eigenvalues and eigenvectors
<span class="math display">\[
A = \begin{bmatrix} 0.7 &amp; 0.2 \\ 0.3 &amp; 0.8 \end{bmatrix}
\qquad
\begin{array}{cc}
\lambda_1 = 1  &amp; \lambda_2 = .5 \\
\mathsf{v}_1 = \begin{bmatrix} 2 \\ 3 \end{bmatrix} &amp; \mathsf{v}_2 = \begin{bmatrix} 1 \\ -1 \end{bmatrix} 
\end{array}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Diagonalize <span class="math inline">\(A\)</span>.</li>
<li>What can you say about <span class="math inline">\(\displaystyle{\lim_{n \to \infty}} A^n\)</span>?</li>
<li>Give a formula for <span class="math inline">\(A^n \mathsf{x}_0\)</span> if <span class="math inline">\(\mathsf{x}_0 = \begin{bmatrix} 25 \\ 0 \end{bmatrix}\)</span> in terms of the eigenbasis.</li>
<li>What is <span class="math inline">\(\displaystyle{\lim_{n \to \infty}} A^n \begin{bmatrix} 25 \\ 0 \end{bmatrix}\)</span>?</li>
</ol>
</div>
<div id="section-62" class="section level3" number="20.3.9">
<h3><span class="header-section-number">20.3.9</span> </h3>
<p>The matrix <span class="math inline">\(A\)</span> below has the given eigenvalues and eigenvectors.
<span class="math display">\[
A = \left[
\begin{array}{cc}
 \frac{1}{2} &amp; \frac{1}{5} \\
 -\frac{2}{5} &amp; \frac{9}{10} \\
\end{array}
\right]
\qquad
\begin{array}{c}
\lambda = .7  \pm .2 i \\
\mathsf{v} = \begin{bmatrix} \frac{1}{2} \\ 1 \end{bmatrix} \pm   \begin{bmatrix} -\frac{1}{2} \\ 0 \end{bmatrix} i
\end{array}\hskip5in
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Factor <span class="math inline">\(A=PRP^{-1}\)</span> where <span class="math inline">\(R\)</span> is a rotation-dilation matrix.</li>
<li>What is the angle of rotation?</li>
<li>What is the factor of dilation?</li>
</ol>
</div>
<div id="section-63" class="section level3" number="20.3.10">
<h3><span class="header-section-number">20.3.10</span> </h3>
<p>In a 1962 study of rainfall in Tel Aviv, it was determined that if today is a wet day, then the probability that tomorrow will be wet is 0.662 and the probability that tomorrow it will be dry is 0.338. If today is a dry day, then the probability that tomorrow is wet is 0.250 and the probability that tomorrow is dry will be 0.75. From this I computed the following:
<span class="math display">\[
A = \begin{bmatrix} 0.662 &amp; 0.25 \\ 0.338 &amp; 0.75\end{bmatrix};
\qquad
\begin{array}{cc}
 \lambda_1 = 1.0 &amp; \lambda_2 = 0.412 \\
 \mathsf{v}_1 = \begin{bmatrix}-0.595 \\ -0.804 \end{bmatrix} &amp; \quad \mathsf{v}_2 = \begin{bmatrix}-0.707\\ 0.707 \end{bmatrix}
 \end{array}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>If Monday is a dry day, what is the probability that Wednesday will be wet?</li>
<li>In the long-run, what is the distribution of wet and dry days?</li>
</ol>
</div>
<div id="section-64" class="section level3" number="20.3.11">
<h3><span class="header-section-number">20.3.11</span> </h3>
<p>A population of female bison is split into three groups: juveniles who are
less than one year old; yearlings between one and two years old; and adults who
are older than two years. Each year,</p>
<pre><code> * 80% of the juveniles survive to become yearlings.
 * 90% of the yearlings survive to become adults.
 * 80% of the adults survive.
 * 40% of the adults give birth to a juvenile</code></pre>
<p>Let
<span class="math inline">\(\mathsf{x}_t = \begin{bmatrix} J_t \\ Y_t \\ A_t \end{bmatrix}\)</span> be the
state of the system in year <span class="math inline">\(t\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>Find the Leslie matrix <span class="math inline">\(L\)</span> such that <span class="math inline">\(\mathsf{x}_{t+1} = B \mathsf{x}_t.\)</span>.</li>
<li>Find the eigenvalues of <span class="math inline">\(L\)</span>.</li>
<li>The matrix <span class="math inline">\(L\)</span> has two complex eigenvalues and one real eigenvalue. How do the complex eigenvectors manifest in the trajectory of a population?</li>
<li>What is the long-term behavior of the herd? Will the size of the herd grow, stablilize or shrink? What will be the proportions of juveniles, yearlings and adults in the herd?</li>
</ol>
</div>
<div id="section-65" class="section level3" number="20.3.12">
<h3><span class="header-section-number">20.3.12</span> </h3>
<p>Let <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> be <span class="math inline">\(n \times n\)</span> matrices. Suppose that <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(A\)</span> with eigenvalue <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(B\)</span> with eigenvalue <span class="math inline">\(\mu\)</span> such that <span class="math inline">\(\lambda \not= \mu\)</span>. Is <span class="math inline">\(v\)</span> an eigenvector of either of the matrices below? If so give its eigenvalue.</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A + B\)</span></li>
<li><span class="math inline">\(AB\)</span></li>
</ol>
</div>
<div id="section-66" class="section level3" number="20.3.13">
<h3><span class="header-section-number">20.3.13</span> </h3>
<p>Suppose that <span class="math inline">\(A\)</span> is invertible.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Show that if <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(A\)</span> with eigenvalue <span class="math inline">\(\lambda\)</span>, then <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(A^{-1}\)</span> with eigenvalue <span class="math inline">\(1/\lambda\)</span>.</p></li>
<li><p>If <span class="math inline">\(A\)</span> is diagonalizable with diagonalization <span class="math inline">\(A = P D P^{-1}\)</span>, then show that <span class="math inline">\(A^{-1}\)</span> is diagonalizable and find its diagonalization from that of <span class="math inline">\(A\)</span>.</p></li>
</ol>
</div>
<div id="section-67" class="section level3" number="20.3.14">
<h3><span class="header-section-number">20.3.14</span> </h3>
<p>Suppose that <span class="math inline">\(A\)</span> is an <span class="math inline">\(n \times n\)</span> matrix with eigenvector <span class="math inline">\(\vec w\)</span> of eigenvalue 5 and eigenvector <span class="math inline">\(\vec v\)</span> of eigenvalue -3.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Is <span class="math inline">\(\vec v + \vec w\)</span> an eigenvector of <span class="math inline">\(A\)</span>, and if so, what is its eigenvalue?</p></li>
<li><p>Is <span class="math inline">\(2021 \vec v\)</span> an eigenvector of <span class="math inline">\(A\)</span>, and if so what is its eigenvalue?</p></li>
<li><p>Is <span class="math inline">\(\vec w\)</span> an eigenvector of <span class="math inline">\(A^2\)</span>, and if so what is its eigenvalue?</p></li>
<li><p>Is <span class="math inline">\(\vec v\)</span> an eigenvector of <span class="math inline">\(A - 2021 I_n\)</span> and if so, what is its eigenvalue?</p></li>
</ol>
<!-- ### -->
<!-- Let $\mathsf{v} =  \begin{bmatrix}1 \\ -1 \\ 1 \end{bmatrix}$ and $\mathsf{w}= \begin{bmatrix}5 \\ 2 \\ 3 \end{bmatrix}$. -->
<!-- a. Find $\| \mathsf{v} \|$ and $\| \mathsf{w} \|$. -->
<!-- b. Find the distance between $\mathsf{v}$ and $\mathsf{w}$. -->
<!-- c. Find the cosine of the angle between $\mathsf{v}$ and $\mathsf{w}$. -->
<!-- d. Find $\mbox{proj}_{\mathsf{v}} \mathsf{w}$.  -->
<!-- e. Let $W=\mbox{span} (\mathsf{v}, \mathsf{w})$. Use the residual from the previous projection to create an orthonormal basis $\mathsf{u}_1, \mathsf{u}_2$ for $W$ such that $\mathsf{u}_1$ is a vector in the same direction as $\mathsf{v}$. -->
<!-- ### -->
<!-- Let $\mathsf{u} \neq 0$ be a vector in $\mathbb{R}^n$. Define the function $T: \mathbb{R}^n \rightarrow \mathbb{R}^n$ by -->
<!-- $T(\mathsf{x}) = \mbox{proj}_{\mathsf{u}} \mathsf{x}$. Recall that the kernel of $T$ is the subspace $\mbox{ker}(T) = \{ \mathsf{x} \in \mathbb{R}^n \mid T(x) = \mathbf{0} \}$. Describe  $\mbox{ker}(T)$ as explicitly as you can. -->
<!-- ###  -->
<!--  The vectors $\mathsf{u}_1, \mathsf{u}_2$  form an orthonormal basis of a subspace $W$ of $\mathbb{R}^4$. Find the projection of $\mathsf{v}$ onto $W$ and determine how close $\mathsf{v}$ is to $W$. -->
<!-- $$ -->
<!-- \mathsf{u}_1 = \frac{1}{2}\begin{bmatrix} 1\\ -1\\ -1\\ 1 \end{bmatrix}, \quad -->
<!-- \mathsf{u}_2 =  \frac{1}{2}\begin{bmatrix} 1\\ -1\\ 1\\ -1  \end{bmatrix}, \quad -->
<!-- \mathsf{v} =  \begin{bmatrix}   2\\ 2\\ 4\\ 2 \end{bmatrix}  -->
<!-- $$ -->
</div>
<div id="section-68" class="section level3" number="20.3.15">
<h3><span class="header-section-number">20.3.15</span> </h3>
<p>Consider vectors
<span class="math inline">\(\mathsf{v}_1 = \begin{bmatrix} 1 \\ 1 \\-1 \end{bmatrix}\)</span> and
<span class="math inline">\(\mathsf{v}_2= \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}\)</span> in <span class="math inline">\(\mathbb{R}^3\)</span>.
Let <span class="math inline">\(W=\mbox{span}(\mathsf{v}_1, \mathsf{v}_2)\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Show that <span class="math inline">\(\mathsf{v}_1\)</span> and <span class="math inline">\(\mathsf{v}_2\)</span> are orthogonal.</p></li>
<li><p>Find a basis for <span class="math inline">\(W^{\perp}\)</span>.</p></li>
</ol>
<!-- c. Use orthogonal projections to find the representation of  -->
<!-- $\mathsf{y} = \begin{bmatrix} 8 \\ 0 \\ 2 \end{bmatrix}$ as -->
<!-- $\mathsf{y} = \hat{\mathsf{y}} + \mathsf{z}$ where -->
<!-- $\hat{\mathsf{y}} \in W$ and $\mathsf{z} \in W^{\perp}$. -->
</div>
<div id="section-69" class="section level3" number="20.3.16">
<h3><span class="header-section-number">20.3.16</span> </h3>
<p>Let <span class="math inline">\(W\)</span> be the span of the vectors
<span class="math display">\[
\begin{bmatrix}
1 \\ -2 \\ 1 \\ 0 \\1 
\end{bmatrix}, \quad
\begin{bmatrix}
-1 \\ 3 \\ -1 \\ 1 \\ -1 
\end{bmatrix}, \quad
\begin{bmatrix}
0 \\ 0 \\ 1 \\ 3 \\1 
\end{bmatrix}, \quad
\begin{bmatrix}
0 \\ 2 \\ 0 \\ 0 \\4 
\end{bmatrix}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>Find a basis for <span class="math inline">\(W\)</span>. What is the dimension of this subspace?</li>
<li>Find a basis for <span class="math inline">\(W^{\perp}\)</span></li>
</ol>
<!-- ### -->
<!-- Consider the system $A \mathsf{x} = \mathsf{b}$ given by -->
<!-- $$ -->
<!-- \begin{bmatrix} -->
<!-- 1 & 1 & 1 \\ -->
<!-- 1 & 2 & -1 \\ -->
<!-- 1 & 1 & -1 \\ -->
<!-- 1 & 2 & 1 -->
<!-- \end{bmatrix} -->
<!-- \begin{bmatrix} -->
<!-- x_1\\ x_2 \\ x_3 -->
<!-- \end{bmatrix} -->
<!-- = -->
<!-- \begin{bmatrix} -->
<!-- 4\\ 1 \\ -2 \\ -1 -->
<!-- \end{bmatrix}. -->
<!-- $$ -->
<!-- a. Show that this system is inconsistent. -->
<!-- b. Find the projected value $\hat{\mathsf{b}}$,  and the residual $\mathsf{z}$. -->
<!-- c. How close is your approximate solution to the desired target vector? -->
<!-- ### -->
<!-- Here is an inconsistent system of equations: -->
<!-- $$ -->
<!-- \begin{bmatrix} 1 & 2 \\ 1 & 2 \\ 1 & -1 \end{bmatrix} -->
<!--  \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} =  -->
<!--   \begin{bmatrix} 6\\ 4 \\ -4 \end{bmatrix}  -->
<!-- $$ -->
<!-- a. State the normal equations for this problem (be sure to do all of the necessary matrix multiplications). -->
<!-- b. Find the least squares solution to the problem. -->
<!-- c. How close is your approximate solution to the desired target vector? -->
<!-- ### Watch this!  -->
<!-- The answer to at least one question on Quiz 3 is contained in [this video](https://www.youtube.com/watch?v=O4KCoNvRi6Y). -->
</div>
</div>
<div id="solutions-to-practice-problems-2" class="section level2" number="20.4">
<h2><span class="header-section-number">20.4</span> Solutions to Practice Problems</h2>
<div id="section-70" class="section level3" number="20.4.1">
<h3><span class="header-section-number">20.4.1</span> </h3>
<p>There are three eigenvalues: 1, 2, and <span class="math inline">\(-2\)</span>. We find an eigenvector for each of them.
* Eigenvalue <span class="math inline">\(\lambda = 1\)</span>
<span class="math display">\[
A - I = 
\left[
\begin{array}{rrr}
1 &amp; -1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
-2 &amp; 5 &amp; -3 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; -1 &amp; 0 \\
0 &amp; 3 &amp; -3 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; -1 &amp; 0 \\
0 &amp; 1 &amp; -1 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; 0 &amp; -1 \\
0 &amp; 1 &amp; -1 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\]</span>
So one eigenvector is <span class="math inline">\([1,1,1]^{\top}\)</span></p>
<ul>
<li><p>Eigenvalue <span class="math inline">\(\lambda = 2\)</span>
<span class="math display">\[
A - 2I = 
\left[
\begin{array}{rrr}
0 &amp; -1 &amp; 0 \\
0 &amp; -1 &amp; 0 \\
-2 &amp; 5 &amp; -4 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
-2 &amp; 5 &amp; -4 \\
0 &amp; -1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
-2 &amp; 0 &amp; -4 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; 0 &amp; 2 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\]</span>
So one eigenvector is <span class="math inline">\([-2,0,1]^{\top}\)</span></p></li>
<li><p>Eigenvalue <span class="math inline">\(\lambda = -2\)</span>
<span class="math display">\[
A - 2I = 
\left[
\begin{array}{rrr}
4 &amp; -1 &amp; 0 \\
0 &amp; 3 &amp; 0 \\
-2 &amp; 5 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
4 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
-2 &amp; 0 &amp; 0 \\
\end{array}
\right]
\sim
\left[
\begin{array}{rrr}
1 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 0 \\
\end{array}
\right]
\]</span>
So one eigenvector is <span class="math inline">\([0,0,1]^{\top}\)</span></p></li>
</ul>
</div>
<div id="section-71" class="section level3" number="20.4.2">
<h3><span class="header-section-number">20.4.2</span> </h3>
<p>In this problem, we are to think about the geometry of a 2D transformation, and see if we can find any vectors which get re-scaled by the transformation. The direction of these vectors cannot change (other than to flip to the opposite direction).</p>
<ol style="list-style-type: lower-alpha">
<li><p>This maps all of <span class="math inline">\(\mathbb{R}^2\)</span> to a line. Therefore it is not one-to-one, nor onto, and so it is not invertible. This means that <span class="math inline">\(\lambda = 0\)</span> is an eigenvalue Any vector that is already on the line must stay on the line, so it is an eigenvector, but we don’t know its eigenvalue. Thus, the eigenvalues are <span class="math inline">\(\lambda_1 = 0\)</span> and <span class="math inline">\(\lambda_2\)</span> we don’t know.</p></li>
<li><p>There are two kinds of eigenvectors. Those vectors on the line are fixed, so they are eigenvectors of eigenvalue 1. Vectors that are perpendicular to the line get sent to their negatives, so they are eigenvectors of eigenvalue <span class="math inline">\(-1\)</span>. Thus, the eigenvalues are <span class="math inline">\(\lambda_1 = 1\)</span> and <span class="math inline">\(\lambda_2=-1\)</span>.</p></li>
</ol>
<ul>
<li>Perhaps this one is easiest to understand by looking at a particular example. Let’s look at a reflection across the <span class="math inline">\(y\)</span>-axis. This means that <span class="math inline">\(A [ x, y]^{\top} = [-x, y]^{\top}\)</span>. In particular, we have <span class="math inline">\(A [ 1, 0]^{\top} = [ -x, 0]^{\top} = - [ x, 0]^{\top}\)</span>. So <span class="math inline">\(-1\)</span> is an eigenvalue. Meanwhile, we also have <span class="math inline">\(A [ 0, 1]^{\top} = [ 0, 1]^{\top}\)</span> So 1 is an eigenvalue.</li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>In this transformation, every vector gets sent to its negative.
<span class="math display">\[
T\left( \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \right)
= \begin{bmatrix} -x_1 \\ -x_2 \end{bmatrix}
= \begin{bmatrix} -1 &amp; 0 \\ 0 &amp; -1 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
\]</span>
This means that every vector is an eigenvector of eigenvalue <span class="math inline">\(-1\)</span>. The eigenvalues are <span class="math inline">\(\lambda_1 = \lambda_2=-1\)</span>.</p></li>
<li><p>A horizontal shear (we did not talk about these very much) has a matrix of the form
<span class="math display">\[
\begin{bmatrix} 1 &amp; a \\ 0 &amp; 1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
= \begin{bmatrix} x + a y \\ y \end{bmatrix}
\]</span>
It fixes the <span class="math inline">\(x\)</span>-axis since <span class="math inline">\((x,0)^\top\)</span> maps to <span class="math inline">\((x,0)^\top\)</span>, but no other directions are fixed. You can see by the fact that the matrix is upper triangluar that the eigenvalues are on the diagonal and are <span class="math inline">\(\lambda_1 = \lambda_2 = 1\)</span>. Note: if you calculate, you find that the geometric multiplicity of <span class="math inline">\(\lambda = 1\)</span> is 1 (only the <span class="math inline">\(x\)</span>-axis), and this matrix is not diagonalizable. The only eigenspace is the <span class="math inline">\(x\)</span>-axis.</p></li>
</ol>
</div>
<div id="section-72" class="section level3" number="20.4.3">
<h3><span class="header-section-number">20.4.3</span> </h3>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(A\)</span> is not invertible because <span class="math inline">\(0\)</span> is an eigenvalue. <span class="math inline">\(A\)</span> is diagonalizable because it have 5 distinct eigenvalues.</li>
<li><span class="math inline">\(B\)</span> is invertible because <span class="math inline">\(0\)</span> is not an eigenvalue. <span class="math inline">\(B\)</span> is diagonalizable because it have 5 distinct eigenvalues.</li>
<li><span class="math inline">\(C\)</span> is invertible because <span class="math inline">\(0\)</span> is not an eigenvalue. We cannot tell whether <span class="math inline">\(C\)</span> is diagonalizable without more information. The eigenvalue <span class="math inline">\(\lambda=2\)</span> has algebraic multiplicity 2. We need to know whether the geometric multiplicity is 1 or 2.</li>
<li><span class="math inline">\(D\)</span> is not invertible because <span class="math inline">\(0\)</span> is an eigenvalue. We cannot tell whether <span class="math inline">\(D\)</span> is diagonalizable without more information. The eigenvalue <span class="math inline">\(\lambda=3\)</span> has algebraic multiplicity 2. We need to know whether the geometric multiplicity is 1 or 2.</li>
</ol>
</div>
<div id="section-73" class="section level3" number="20.4.4">
<h3><span class="header-section-number">20.4.4</span> </h3>
<ol style="list-style-type: lower-alpha">
<li>No, <span class="math inline">\(A\)</span> is not invertible because <span class="math inline">\(0\)</span> is an eigenvalue.</li>
<li><span class="math inline">\(\mathsf{v} = [1, -2, 1]^{\top}\)</span> is an eigenvector for <span class="math inline">\(\lambda=0\)</span>. Therefore <span class="math inline">\(\mathsf{v} \in \mbox{Nul}(A)\)</span>.</li>
<li>The vector <span class="math inline">\(\mathsf{v} = [0,1,2]^{\top}\)</span> is an eigenvector for <span class="math inline">\(\lambda=1\)</span>. So this is a steady-state vector. (However, the dynamical system will not converge to this steady state because <span class="math inline">\(\lambda=6\)</span> is the dominant eigenvalue.)</li>
<li>When <span class="math inline">\(A=P D P^{-1}\)</span>, we can find the coordinates of a vector with respect to the eigenbasis via multiplication by <span class="math inline">\(P^{-1}\)</span>.</li>
</ol>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="exam-3-review.html#cb322-1" aria-hidden="true" tabindex="-1"></a>Pinv <span class="ot">=</span><span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>),<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">15</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>),<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">30</span>,<span class="dv">2</span><span class="sc">/</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>))</span>
<span id="cb322-2"><a href="exam-3-review.html#cb322-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)</span>
<span id="cb322-3"><a href="exam-3-review.html#cb322-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb322-4"><a href="exam-3-review.html#cb322-4" aria-hidden="true" tabindex="-1"></a>Pinv <span class="sc">%*%</span> v</span></code></pre></div>
<pre><code>##      [,1]
## [1,] -0.2
## [2,]  1.6
## [3,]  0.0</code></pre>
<p>So <span class="math inline">\([ \mathsf{v}]_{\mathcal{B}} = [-1/5, 8/5, 0]^{\top}\)</span>.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li><span class="math inline">\(-\frac{1}{5} \cdot 6^{2020} \cdot \begin{bmatrix} -5 \\ -2 \\ 1 \end{bmatrix} + \frac{8}{5} \cdot \begin{bmatrix} 0 \\ 1 \\ 2 \end{bmatrix}\)</span></li>
</ol>
</div>
<div id="section-74" class="section level3" number="20.4.5">
<h3><span class="header-section-number">20.4.5</span> </h3>
<p>This system scales by <span class="math inline">\(\sqrt{1+1} = \sqrt{2}\)</span> and it rotates by <span class="math inline">\(\tan^{-1} (1/1) = \pi/4\)</span>.</p>
</div>
<div id="section-75" class="section level3" number="20.4.6">
<h3><span class="header-section-number">20.4.6</span> </h3>
<p>We have
<span class="math display">\[
\begin{bmatrix} a &amp; -b \\ b &amp; a \end{bmatrix} = \begin{bmatrix} .97 &amp; -.71\\ .71 &amp; .97 \end{bmatrix} 
\]</span></p>
<p>Let’s turn to RStudio</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="exam-3-review.html#cb324-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> .<span class="dv">97</span></span>
<span id="cb324-2"><a href="exam-3-review.html#cb324-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">=</span> .<span class="dv">71</span></span>
<span id="cb324-3"><a href="exam-3-review.html#cb324-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb324-4"><a href="exam-3-review.html#cb324-4" aria-hidden="true" tabindex="-1"></a>scale <span class="ot">=</span> <span class="fu">sqrt</span>(a<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>b<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb324-5"><a href="exam-3-review.html#cb324-5" aria-hidden="true" tabindex="-1"></a>angle <span class="ot">=</span> <span class="fu">atan</span> (b<span class="sc">/</span>a)</span>
<span id="cb324-6"><a href="exam-3-review.html#cb324-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb324-7"><a href="exam-3-review.html#cb324-7" aria-hidden="true" tabindex="-1"></a>scale</span></code></pre></div>
<pre><code>## [1] 1.202082</code></pre>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="exam-3-review.html#cb326-1" aria-hidden="true" tabindex="-1"></a>angle</span></code></pre></div>
<pre><code>## [1] 0.6318544</code></pre>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="exam-3-review.html#cb328-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">/</span> angle</span></code></pre></div>
<pre><code>## [1] 9.94404</code></pre>
<ol style="list-style-type: lower-alpha">
<li>It takes 10 iterations to rotate past the <span class="math inline">\(x\)</span>-axis.</li>
<li>We are further from the origin because <span class="math inline">\(| \lambda| \approx 1.2 &gt; 1\)</span>.</li>
</ol>
</div>
<div id="section-76" class="section level3" number="20.4.7">
<h3><span class="header-section-number">20.4.7</span> </h3>
<ol style="list-style-type: lower-alpha">
<li>The matrix <span class="math inline">\(A\)</span> is diagonalizable because it has 3 distinct eigenvalues</li>
<li>We must see whether <span class="math inline">\(\lambda=4\)</span> has geometric multiplicty 2 (to match its algebraic multiplicity).</li>
</ol>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="exam-3-review.html#cb330-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rref</span>( <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">2</span>), <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">2</span>), <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>,<span class="sc">-</span><span class="dv">4</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1   -2
## [2,]    0    0    0
## [3,]    0    0    0</code></pre>
<p>We see that <span class="math inline">\(B - 4I\)</span> has two free columns, so <span class="math inline">\(\dim ( \mbox{Nul}(B-4I))=2\)</span>. This means that <span class="math inline">\(\lambda=4\)</span> has geometric multiplicity 2. Therefore <span class="math inline">\(B\)</span> is diagonalizable.</p>
</div>
<div id="section-77" class="section level3" number="20.4.8">
<h3><span class="header-section-number">20.4.8</span> </h3>
<ol style="list-style-type: lower-alpha">
<li>We set <span class="math inline">\(P = \begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}\)</span>. So
<span class="math display">\[
P^{-1} =  - \frac{1}{5} \begin{bmatrix} -1 &amp; -1 \\ -3 &amp; 2 \end{bmatrix}
= \begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}
\]</span>
Or we can find this inverse using RStudio.</li>
</ol>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="exam-3-review.html#cb332-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>),<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb332-2"><a href="exam-3-review.html#cb332-2" aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(A)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.2  0.2
## [2,]  0.6 -0.4</code></pre>
<p>Therefore
<span class="math display">\[
A = \begin{bmatrix} 0.7 &amp; 0.2 \\ 0.3 &amp; 0.8 \end{bmatrix} = 
\begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}
\begin{bmatrix} 1 &amp; 0 \\ 0 &amp; 0.5 \end{bmatrix}
\begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>We compute this as follows:</li>
</ol>
<p><span class="math display">\[
A^n =  
\begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}
\begin{bmatrix} 1 &amp; 0 \\ 0 &amp; 0.5 \end{bmatrix}^n
\begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}=
\begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}
\begin{bmatrix} 1^n &amp; 0 \\ 0 &amp; 0.5^n \end{bmatrix}
\begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}
\]</span>
so
<span class="math display">\[
\lim_{n\to \infty} A^n = 
\begin{bmatrix} 2 &amp; 1 \\ 3 &amp; -1 \end{bmatrix}
\begin{bmatrix} 1 &amp; 0 \\ 0 &amp; 0 \end{bmatrix}
\begin{bmatrix} 0.2 &amp; 0.2 \\ 0.6 &amp; -0.4 \end{bmatrix}
=\begin{bmatrix} 0.4 &amp; 0.4 \\ 0.6 &amp; 0.6 \end{bmatrix}
\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>We need to find the coefficients for <span class="math inline">\(x_0 = [25, 0]^{\top}\)</span>.</li>
</ol>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="exam-3-review.html#cb334-1" aria-hidden="true" tabindex="-1"></a>P <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb334-2"><a href="exam-3-review.html#cb334-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">0</span>)</span>
<span id="cb334-3"><a href="exam-3-review.html#cb334-3" aria-hidden="true" tabindex="-1"></a><span class="fu">solve</span>(P,v)</span></code></pre></div>
<pre><code>## [1]  5 15</code></pre>
<p>So the formula is
<span class="math display">\[
5 \begin{bmatrix} 2 \\ 3 \end{bmatrix} + 15 \left( \frac{1}{2}  \right)^n \begin{bmatrix} 1 \\ -1 \end{bmatrix} 
\]</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>This converges to <span class="math inline">\(5 \begin{bmatrix} 2 \\ 3 \end{bmatrix}\)</span>.</li>
</ol>
</div>
<div id="section-78" class="section level3" number="20.4.9">
<h3><span class="header-section-number">20.4.9</span> </h3>
<ol style="list-style-type: lower-alpha">
<li>We have
<span class="math display">\[
A = \left[
\begin{array}{cc}
 \frac{1}{2} &amp; \frac{1}{5} \\
 -\frac{2}{5} &amp; \frac{9}{10} \\
\end{array}
\right]
=
\begin{bmatrix}
-1/2 &amp; 1/2 \\ 0 &amp; 1
\end{bmatrix}
\begin{bmatrix}
0.7 &amp; -0.2 \\ 0.2 &amp; 0.7
\end{bmatrix}
\begin{bmatrix}
-2 &amp; 1 \\ 0 &amp; 1
\end{bmatrix}
\]</span>
Here are some R calculations to check the answer for (a) and to find the values for (b) and (c).</li>
</ol>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="exam-3-review.html#cb336-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="sc">-</span><span class="dv">2</span><span class="sc">/</span><span class="dv">5</span>), <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="dv">9</span><span class="sc">/</span><span class="dv">10</span>))</span>
<span id="cb336-2"><a href="exam-3-review.html#cb336-2" aria-hidden="true" tabindex="-1"></a>A</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.5  0.2
## [2,] -0.4  0.9</code></pre>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="exam-3-review.html#cb338-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 0.7+0.2i 0.7-0.2i
## 
## $vectors
##                      [,1]                 [,2]
## [1,] 0.4082483-0.4082483i 0.4082483+0.4082483i
## [2,] 0.8164966+0.0000000i 0.8164966+0.0000000i</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="exam-3-review.html#cb340-1" aria-hidden="true" tabindex="-1"></a>P <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb340-2"><a href="exam-3-review.html#cb340-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(.<span class="dv">7</span>,.<span class="dv">2</span>),<span class="fu">c</span>(<span class="sc">-</span>.<span class="dv">2</span>,.<span class="dv">7</span>))</span>
<span id="cb340-3"><a href="exam-3-review.html#cb340-3" aria-hidden="true" tabindex="-1"></a>Pinv <span class="ot">=</span> <span class="fu">solve</span>(P)</span>
<span id="cb340-4"><a href="exam-3-review.html#cb340-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb340-5"><a href="exam-3-review.html#cb340-5" aria-hidden="true" tabindex="-1"></a>Pinv</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   -2    1
## [2,]    0    1</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="exam-3-review.html#cb342-1" aria-hidden="true" tabindex="-1"></a>P <span class="sc">%*%</span> C <span class="sc">%*%</span> Pinv</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.5  0.2
## [2,] -0.4  0.9</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="exam-3-review.html#cb344-1" aria-hidden="true" tabindex="-1"></a><span class="fu">atan</span>(.<span class="dv">2</span><span class="sc">/</span>.<span class="dv">7</span>)</span></code></pre></div>
<pre><code>## [1] 0.2782997</code></pre>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="exam-3-review.html#cb346-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(.<span class="dv">7</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> .<span class="dv">2</span><span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.728011</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>The angle of rotation is <span class="math inline">\(\tan^{-1} (.2/.7) = 0.278\)</span> radians</li>
<li>The dilation factor is <span class="math inline">\(\sqrt{0.49 + 0.04} = \sqrt{0.53} = 0.728\)</span>.</li>
</ol>
</div>
<div id="section-79" class="section level3" number="20.4.10">
<h3><span class="header-section-number">20.4.10</span> </h3>
<p>Let’s use RStudio.</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="exam-3-review.html#cb348-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="fl">0.662</span>, <span class="fl">0.338</span>),<span class="fu">c</span>(<span class="fl">0.25</span>,  <span class="fl">0.75</span>))</span>
<span id="cb348-2"><a href="exam-3-review.html#cb348-2" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> A <span class="sc">%*%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##       [,1]
## [1,] 0.353
## [2,] 0.647</code></pre>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="exam-3-review.html#cb350-1" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">=</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.595</span>, <span class="sc">-</span><span class="fl">0.804</span> )</span>
<span id="cb350-2"><a href="exam-3-review.html#cb350-2" aria-hidden="true" tabindex="-1"></a>v1<span class="sc">/</span><span class="fu">sum</span>(v1)</span></code></pre></div>
<pre><code>## [1] 0.4253038 0.5746962</code></pre>
<ol style="list-style-type: lower-alpha">
<li>If Monday is dry, then the probability of a wet Wednesday is <span class="math inline">\(0.353\)</span>. The easiest way to calculate this <span class="math inline">\(A^2 \begin{bmatrix} 1 \\ 0 \end{bmatrix}.\)</span></li>
<li>In the long run, <span class="math inline">\(42.5\%\)</span> of days are wet and <span class="math inline">\(57.5\%\)</span> of days are dry.</li>
</ol>
</div>
<div id="section-80" class="section level3" number="20.4.11">
<h3><span class="header-section-number">20.4.11</span> </h3>
<ol style="list-style-type: lower-alpha">
<li>Here is the Leslie matrix, as well as some eigensystem computations.</li>
</ol>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="exam-3-review.html#cb352-1" aria-hidden="true" tabindex="-1"></a>L <span class="ot">=</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">8</span>,<span class="dv">0</span>),<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">9</span>),<span class="fu">c</span>(.<span class="dv">4</span>,<span class="dv">0</span>,.<span class="dv">8</span>))</span>
<span id="cb352-2"><a href="exam-3-review.html#cb352-2" aria-hidden="true" tabindex="-1"></a>L</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]  0.0  0.0  0.4
## [2,]  0.8  0.0  0.0
## [3,]  0.0  0.9  0.8</code></pre>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="exam-3-review.html#cb354-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">vals =</span> <span class="fu">eigen</span>(L)<span class="sc">$</span>values)</span></code></pre></div>
<pre><code>## [1]  1.0575217+0.0000000i -0.1287609+0.5057227i -0.1287609-0.5057227i</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="exam-3-review.html#cb356-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Mod</span>(vals)</span></code></pre></div>
<pre><code>## [1] 1.0575217 0.5218571 0.5218571</code></pre>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="exam-3-review.html#cb358-1" aria-hidden="true" tabindex="-1"></a>vecs <span class="ot">=</span> <span class="fu">eigen</span>(L)<span class="sc">$</span>vectors</span>
<span id="cb358-2"><a href="exam-3-review.html#cb358-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">=</span> vecs[,<span class="dv">1</span>]</span>
<span id="cb358-3"><a href="exam-3-review.html#cb358-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Re</span>(v<span class="sc">/</span><span class="fu">sum</span>(v)) <span class="co"># get it to sum to 1 AND remove the 0 imaginary part</span></span></code></pre></div>
<pre><code>## [1] 0.2272578 0.1719172 0.6008250</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>The eigenvalues are <span class="math inline">\(1.058, -0.129 \pm 0.506 i\)</span>. The complex eigenvalues have length 0.52, so they shrink away pretty quickly.</li>
<li>If we start outside of the span of the dominant eigenvalue, then the trajectory oscillate slightly until it settles into the direction of the dominant eigevector, with an overall growth trend of <span class="math inline">\(1.058\)</span>, or <span class="math inline">\(5.8\%\)</span>.</li>
<li>The size of the herd grows. The proportions are <span class="math inline">\([0.227, 0.172, 0.601]\)</span>.</li>
</ol>
</div>
<div id="section-81" class="section level3" number="20.4.12">
<h3><span class="header-section-number">20.4.12</span> </h3>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\((A + B) v = A v + B v = \lambda v + \mu v = (\lambda + \mu) v\)</span>, so yes, <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(A+B\)</span> of eigenvalue <span class="math inline">\(\lambda + \mu\)</span>.</p></li>
<li><p><span class="math inline">\(A B v = A (B v) = A (\mu v) = \mu (A v) = \mu \lambda v\)</span>, so yes, <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(AB\)</span> of eigenvalue <span class="math inline">\(\lambda\mu\)</span>.</p></li>
</ol>
</div>
<div id="section-82" class="section level3" number="20.4.13">
<h3><span class="header-section-number">20.4.13</span> </h3>
<ol style="list-style-type: lower-alpha">
<li>We are given <span class="math inline">\(A v = \lambda v\)</span>. Thus,</li>
</ol>
<p><span class="math display">\[
\begin{array}{cccl}
A v &amp; = &amp; \lambda v &amp; \text{given} \\
A^{-1} A v &amp; = &amp; \lambda A^{-1} v &amp; \text{multiply on the left by $A^{-1}$} \\
v &amp; = &amp; \lambda A^{-1} v \\
\frac{1}{\lambda} v &amp; = &amp;  A^{-1} v \\
\end{array}
\]</span>
This shows that <span class="math inline">\(A^{-1} v = \frac{1}{\lambda} v\)</span> so <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\(A^{-1}\)</span> with eigenvalue <span class="math inline">\(\frac{1}{\lambda}\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>(method 1) If <span class="math inline">\(A\)</span> is diagonal, then there is a basis <span class="math inline">\(\{v_1, v_2, \ldots, v_n\}\)</span> of eigenvectors of <span class="math inline">\(A\)</span> with eigenvalues <span class="math inline">\(\lambda_1, \lambda_2, \ldots, \lambda_n\)</span>. By the previous part, <span class="math inline">\(\{v_1, v_2, \ldots, v_n\}\)</span> are eigenvectors of <span class="math inline">\(A^{-1}\)</span> with eigenvalues <span class="math inline">\(1/\lambda_1, 1/\lambda_2, \ldots, 1/\lambda_n\)</span>. Thus <span class="math inline">\(A^{-1}\)</span> has the same eigenbasis, and the diagonalization of <span class="math inline">\(A^{-1}\)</span> is
<span class="math display">\[
A^{-1} = 
\underbrace{
\begin{bmatrix} 
\vert &amp;\vert &amp;&amp;\vert \\
v_1 &amp; v_2 &amp; \cdots &amp; v_n \\
\vert &amp;\vert &amp;&amp;\vert \\
\end{bmatrix}
}_P
\begin{bmatrix} 
1/\lambda_1 &amp; &amp; &amp; \\
&amp;  1/\lambda_2 &amp; &amp; \\
&amp;    &amp; \ddots \\
&amp; &amp;   &amp;   1/\lambda_n \\
\end{bmatrix} P^{-1}
\]</span>
(method 2) If <span class="math inline">\(A = P D P^{-1}\)</span> then by the fact that the order reverses when computing inverses (the shoes-and-socks property), we have <span class="math inline">\(A^{-1} = (P D P^{-1})^{-1} = (P^{-1})^{-1} D^{-1} P^{-1} = P D^{-1} P^{-1}.\)</span> Furthermore <span class="math inline">\(D^{-1}\)</span> is a diagonal matrix such that
<span class="math display">\[
\text{if} \qquad D = 
\begin{bmatrix} 
\lambda_1 &amp; &amp; &amp;  \\
&amp;  \lambda_2 &amp; &amp;  \\
&amp;    &amp; \ddots &amp; \\
&amp;   &amp;   &amp; \lambda_n \\
\end{bmatrix}
\qquad\text{then}\qquad
D^{-1} = 
\begin{bmatrix} 
1/\lambda_1 &amp; &amp; &amp;  \\
&amp;  1/\lambda_2 &amp; &amp;  \\
&amp;   &amp; &amp; \ddots &amp; \\
&amp;   &amp; &amp;  &amp; 1/\lambda_n \\
\end{bmatrix}
\]</span>
Note that <span class="math inline">\(A\)</span> is invertible, 0 is not an eigenvalue, so each <span class="math inline">\(1/\lambda_i\)</span> does not cause division by 0.</li>
</ol>
</div>
<div id="section-83" class="section level3" number="20.4.14">
<h3><span class="header-section-number">20.4.14</span> </h3>
<p>We are given that <span class="math inline">\(A w = 5 w\)</span> and <span class="math inline">\(A v = -3 v\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(A (v + w) = A v + A w = -3 v + 5 w \not = \lambda(v + w)\)</span> for any <span class="math inline">\(\lambda\)</span>, so <span class="math inline">\(v + w\)</span> is not an eigenvector of <span class="math inline">\(A\)</span>. Note: it would be if they had the same eigenvalue.</p></li>
<li><p><span class="math inline">\(A (2021 v) = 2021 A v = 2021 (-3) v = (-3) (2021 v)\)</span> so <span class="math inline">\(2021 v\)</span> is an eigenvector also of eigenvalue <span class="math inline">\(-3\)</span>.</p></li>
<li><p><span class="math inline">\(A^2 w = A (A w) = A (5 w) = 5 (A w) = 5 (5 w) = 25 w\)</span>, so <span class="math inline">\(w\)</span> is an eigenvector of <span class="math inline">\(A^2\)</span> of eigenvalue 25.</p></li>
<li><p><span class="math inline">\((A - 20201I_n)v = A v - 2021 I_n v = -3 v - 2021 v = -2024 v\)</span>, so <span class="math inline">\(v\)</span> is an eigenvector of <span class="math inline">\((A - 20201I_n)\)</span> of eigenvalue <span class="math inline">\(-2024\)</span>.</p></li>
</ol>
<!-- ##  -->
<!-- a. -->
<!-- \begin{align} -->
<!-- \| \mathsf{v} \| &= \sqrt{ \mathsf{v} \cdot \mathsf{v}} = \sqrt{1+1+1} = \sqrt{3} \\ -->
<!-- \| \mathsf{w} \| &= \sqrt{ \mathsf{w} \cdot \mathsf{vw}} = \sqrt{25+4+9} = \sqrt{38} \\ -->
<!-- \end{align} -->
<!-- b. We have $\mathsf{v} - \mathsf{w} = \begin{bmatrix} -4 \\ -3 \\ -2 \end{bmatrix}$ and so -->
<!-- $$ -->
<!-- \| \mathsf{v} - \mathsf{w}\|  = \sqrt{16+9+4} = \sqrt{29}  -->
<!-- $$ -->
<!-- c.  -->
<!-- $$  -->
<!-- \cos \theta = \frac{\mathsf{v} \cdot \mathsf{w}}{\| \mathsf{v}  \| \, \|\mathsf{w} \| } -->
<!-- = \frac{5-2+3}{\sqrt{3} \, \sqrt{38} } = \frac{2\sqrt{3}}{\sqrt{38} } -->
<!-- $$ -->
<!-- d.  -->
<!-- $$ -->
<!-- \hat{\mathsf{w}} = \mbox{proj}_{\mathsf{v}} \mathsf{w} = \frac{\mathsf{v} \cdot \mathsf{w}}{ \mathsf{v} \cdot \mathsf{v} } \, \mathsf{v} = \frac{5-2+3}{1+1+1}  \mathsf{v}  = 2 \mathsf{v} =  -->
<!-- \begin{bmatrix} -->
<!-- 2 \\ -2 \\ 2  -->
<!-- \end{bmatrix} -->
<!-- $$ -->
<!-- e. Using $\hat{\mathsf{w}}$ from the previous problem, we know that  -->
<!-- $$ -->
<!-- \mathsf{z} = \mathsf{w} - \hat{\mathsf{w}} = \begin{bmatrix} 5 \\ 2 \\ 3 \end{bmatrix}  -  \begin{bmatrix} 2 \\ -2 \\ 2  \end{bmatrix} = -->
<!-- \begin{bmatrix} 3 \\ 4 \\ 1  \end{bmatrix} -->
<!-- $$  -->
<!-- is orthogonal to $\mathsf{v}$.So an orthonormal basis is -->
<!-- $$ -->
<!-- \frac{1}{\sqrt{3}} \begin{bmatrix} -->
<!-- 1 \\ -1 \\ 1 -->
<!-- \end{bmatrix} \quad \mbox{and} \quad -->
<!-- \frac{1}{\sqrt{26}} \begin{bmatrix} -->
<!-- 3 \\ 4 \\ 1 -->
<!-- \end{bmatrix} -->
<!-- $$ -->
<!-- ### -->
<!-- Here are a few ways to describe $\mbox{ker}(T)$. -->
<!-- a. $\mbox{ker}(T) = \{ \mathsf{x} \in \mathbb{R}^n \mid \mathsf{x} \cdot \mathsf{u} = 0 \}$. -->
<!-- b. $\mbox{ker}(T)$ is the set of vectors that are orthogonal to $\mathsf{u}$. -->
<!-- c. Let $A$ be the $1 \times n$ matrix $\mathsf{u}^{\top}$. Then $\mbox{ker}(T)= \mbox{Nul}(A)$. -->
<!-- ### -->
<!-- We have $\mathsf{u}_1 \cdot \mathsf{v} = 2-2-4+2=-2$ and $\mathsf{u}_1 \cdot \mathsf{v} = 2-2+4-2=2$ so -->
<!-- $$ -->
<!-- \hat{\mathsf{v}} = \mbox{proj}_W \mathsf{v} = - \mathsf{u}_1 +  \mathsf{u}_2 =  -->
<!-- -\frac{1}{2} \begin{bmatrix} -->
<!-- 1 \\ -1 \\ -1 \\ 1  -->
<!-- \end{bmatrix} -->
<!-- + -->
<!-- \frac{1}{2} -->
<!-- \begin{bmatrix} -->
<!-- 1 \\ -1 \\ 1 \\ -1  -->
<!-- \end{bmatrix} -->
<!-- = -->
<!-- \begin{bmatrix} -->
<!-- 0 \\ 0 \\ 1 \\ -1  -->
<!-- \end{bmatrix} -->
<!-- $$ -->
<!-- with residual vector  -->
<!-- $$ -->
<!-- \mathsf{z} = \mathsf{v} - \hat{\mathsf{v}} -->
<!-- = \begin{bmatrix} -->
<!-- 2 \\ 2 \\ 4 \\ 2  -->
<!-- \end{bmatrix} -->
<!-- - -->
<!-- \begin{bmatrix} -->
<!-- 0 \\ 0 \\ 1 \\ -1  -->
<!-- \end{bmatrix} -->
<!-- = -->
<!-- \begin{bmatrix} -->
<!-- 2 \\ 2 \\ 3 \\ 3  -->
<!-- \end{bmatrix} -->
<!-- $$ -->
<!-- and the distance is $\| \mathsf{z} \| = \sqrt{4+4+9+9} = \sqrt{26}$. -->
<!-- ### -->
<!-- a. $\mathsf{v}_1 \cdot \mathsf{v}_2 = 1 +2 - 3 =0$. -->
<!-- b. We must find $\mbox{Nul}(A)$ where  -->
<!-- $A = \begin{bmatrix} \mathsf{v}_1^{\top} \\ \mathsf{v}_2^{\top}\end{bmatrix}$. -->
<!-- $$ -->
<!-- \begin{bmatrix} -->
<!-- 1 & 1 & -1 \\ -->
<!-- 1 & 2 & 3 -->
<!-- \end{bmatrix} -->
<!-- \longrightarrow -->
<!-- \begin{bmatrix} -->
<!-- 1 & 1 & -1 \\ -->
<!-- 0 & 1 & 4 -->
<!-- \end{bmatrix} -->
<!-- \longrightarrow -->
<!-- \begin{bmatrix} -->
<!-- 1 & 0 & -5 \\ -->
<!-- 0 & 1 & 4 -->
<!-- \end{bmatrix} -->
<!-- $$ -->
<!-- so the vector $\begin{bmatrix} 5 \\ -4 \\ 1 \end{bmatrix}$ is a basis for $W^{\perp}$ -->
<!-- c. We have -->
<!-- \begin{align} -->
<!-- \hat{\mathsf{y}} &= -->
<!-- \frac{\mathsf{y} \cdot \mathsf{v_1}}{\mathsf{v_1} \cdot \mathsf{v_1}} \, \mathsf{v_1} + -->
<!-- \frac{\mathsf{y} \cdot \mathsf{v_2}}{\mathsf{v_2} \cdot \mathsf{v_2}} \, \mathsf{v_2} -->
<!-- = -->
<!-- \frac{8-2}{1+1+1} \mathsf{v_1} + \frac{8+6}{1+4+9} \mathsf{v_2} \\ -->
<!-- &= -->
<!-- 2\mathsf{v_1} +\mathsf{v_2} -->
<!-- = \begin{bmatrix} 2 \\ 2 \\ -2 \end{bmatrix} + \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} -->
<!-- = \begin{bmatrix} 3 \\ 4 \\ 1 \end{bmatrix} -->
<!-- \end{align} -->
<!-- and so  -->
<!-- $$ -->
<!-- \mathsf{z} = \mathsf{y} - \hat{\mathsf{y}} -->
<!-- = \begin{bmatrix} 8 \\ 0 \\ 2 \end{bmatrix} - \begin{bmatrix} 3 \\ 4 \\ 1 \end{bmatrix} -->
<!-- = \begin{bmatrix} 5 \\ -4 \\ 1 \end{bmatrix}. -->
<!-- $$ -->
<!-- ### -->
<!-- a .We will answer this one using RStudio. -->
<!-- ```{r, echo=TRUE} -->
<!-- A = cbind(c(1,-2,1,0,1), c(-1,3,-1,1,-1), c(0,0,1,3,1), c(0,2,0,0,4)) -->
<!-- rref(A) -->
<!-- ``` -->
<!-- So we need all four vectors to span the column space. -->
<!-- b. We obtain a basis for $W^{\perp}$ by finding $\mbox{Nul(A^{\top})}$ So let's row reduce $A^{\top}$ -->
<!-- ```{r, echo=TRUE} -->
<!-- rref(t(A)) -->
<!-- ``` -->
<!-- The vector  $\begin{bmatrix} 2 \\ -2 \\ -7 \\ 2 \\ 1\end{bmatrix}$ spans $W^{\perp}$ -->
<!-- ### -->
<!-- a. -->
<!-- ```{r echo=TRUE} -->
<!-- A = cbind(c(1,1,1,1), c(1,2,1,2),c(1,-1,-1,1)) -->
<!-- b  = c(4,1,-2,-1) -->
<!-- rref(cbind(A,b)) -->
<!-- ``` -->
<!-- There is a pivot in the last column of this augmented matrix, so this system is inconsistent. -->
<!-- b. -->
<!-- Here is the least squares calculation. -->
<!-- ```{r, echo=TRUE} -->
<!-- #solve the normal equation -->
<!-- (xhat = solve(t(A) %*% A, t(A) %*% b)) -->
<!-- # find the projection -->
<!-- (bhat = A %*% xhat) -->
<!-- # find the residual vector -->
<!-- (z = b - bhat) -->
<!-- # check that z is orthogonal to Col(A) -->
<!-- t(A) %*% z -->
<!-- # measure the distance between bhat and b -->
<!-- sqrt( t(z) %*% z) -->
<!-- ``` -->
<!-- The projection is $\hat{\mathsf{b}} = [2,-1,0,1]^{\top}$.  -->
<!-- The residual is $\mathsf{z} = [2,2,-2,-2]^{\top}$ -->
<!-- c. The distance of between $\mathsf{b}$ and  $\hat{\mathsf{b}}$ is  -->
<!-- $$ -->
<!-- \| = \| \mathsf{z} \| = \sqrt{4+4+4+4} = \sqrt{16} = 4. -->
<!-- $$ -->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exam-2-review.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
